// Every transport is intercepted. Source writes affect synthetic rows only.
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await browser.newPage({viewport:{width:1440,height:900},timezoneId:'Asia/Seoul',hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.clock.setFixedTime(new Date('2026-10-04T03:00:00Z'));await fixture(p);fs.mkdirSync('test-results/all-views',{recursive:true});
 await p.evaluate(async()=>{
  const patch=(kind,start,end,a,b)=>OnekanPeriod.patch(kind,{allDay:!a,startDate:start,endDate:end,startTime:a||'',endTime:b||''});
  mockRows.tok_events=[{id:'same',user_id:'test',title:'같은 ID 일정',category_id:'samegroup',shared_category_id:'c',...patch('event','2026-10-04','2026-10-04','09:07','10:08')},{id:'multi',user_id:'test',title:'여러 날 일정',...patch('event','2026-10-02','2026-10-06')},{id:'midnight',user_id:'test',title:'00시 종료',...patch('event','2026-10-03','2026-10-04','23:00','00:00')},{id:'legacy',user_id:'test',title:'종료 없는 일정',event_date:'2026-10-04',event_time:'13:00',duration_minutes:null}];
  mockRows.tok_todos=[{id:'same',user_id:'test',title:'같은 ID 할일',group_id:'samegroup',tag_id:'c',project_id:'p',...patch('todo','2026-10-04','2026-10-04','09:30','10:30')},{id:'undated',user_id:'test',title:'날짜 없는 할일',start_date:null,is_done:false},{id:'night',user_id:'test',title:'반복 할일',repeat_unit:'day',repeat_interval:1,end_date:'2026-10-31',group_id:'samegroup',tag_id:'c',project_id:'p',...patch('todo','2026-10-03','2026-10-04','23:00','01:00')}];
  const base={user_id:'test',is_active:true,start_date:'2026-10-03',end_date:'2026-10-10',repeat_unit:'day',repeat_interval:1};
  mockRows.tok_habits=[{...base,id:'same',name:'같은 ID 습관',group_id:'samegroup',category_id:'c',project_id:'p',...patch('habit','2026-10-03','2026-10-04','23:00','01:00')},{...base,id:'archive',name:'보관된 기록',is_active:false,...patch('habit','2026-10-03','2026-10-03','15:00','17:00')},{...base,id:'ended',name:'종료된 기록',end_date:'2026-10-02',...patch('habit','2026-10-01','2026-10-01')},{...base,id:'late',name:'지연 기록',repeat_unit:'month',start_date:'2026-10-01',...patch('habit','2026-10-01','2026-10-01')}];
  mockRows.tok_habit_logs=[{id:'snapshot',habit_id:'archive',done_date:'2026-10-02',start_minute:1380,duration_minutes:120,occurrence_end_date:'2026-10-03'},{id:'old',habit_id:'ended',done_date:'2026-10-01',start_minute:540,duration_minutes:null},{id:'late-log',habit_id:'late',done_date:'2026-10-04',start_minute:null,duration_minutes:null}];
  mockRows.tok_habit_skips=[{habit_id:'ended',skip_date:'2026-10-02'}];mockRows.tok_habit_pauses=[{habit_id:'archive',paused_at:'2026-10-04',resumed_at:null}];
  mockRows.tok_event_categories=[{id:'samegroup',name:'회사',color:'#447799'}];mockRows.tok_item_groups=[{id:'samegroup',kind:'todo',name:'회사'},{id:'samegroup',kind:'habit',name:'회사'}];mockRows.tok_habit_categories=[{id:'c',name:'공용 범주',color:'#9374ac'}];mockRows.tok_projects=[{id:'p',name:'목표',is_active:true}];mockRows.tok_someday=[{id:'someday',title:'통합에서 제외'}];mockRows.tok_time_blocks=[{id:'block',name:'오전',start_minute:540,end_minute:720}];
  await loadAll();showPage('all');allViews.selectDate('2026-10-04');mockWrites.length=0;
 });
 const writes=()=>p.evaluate(()=>mockWrites.length),view=mode=>p.locator('#pageSidebarItems [data-sidebar-tab='+mode+']:visible, #allViewTabs [data-tab='+mode+']:visible').click();
 assert.equal(await p.evaluate(()=>allViews.state().span),'month');assert.deepEqual(await p.locator('#allSidebarTypes .aft-title').allTextContents(),['내 일정','다른 캘린더']); /* 2026-10-10 구글 캘린더식 사이드바 */ // 2026-10-10: 종류 3개(+범주·그룹 눈), 옛 상태 선택은 숨김(완료도 체크로 보여줌)
 const model=await p.evaluate(()=>allViews.displayRows());assert.equal(new Set(model.map(r=>r.id)).size,model.length);for(const k of ['event','todo','habit'])assert(model.some(r=>r.kind===k&&r.source_id==='same'));
 assert.equal(model.find(r=>r.record_id==='snapshot').duration_minutes,120);assert.equal(model.find(r=>r.record_id==='snapshot').start_minute,1380);assert.equal(model.find(r=>r.record_id==='old').duration_minutes,null);assert.equal(model.find(r=>r.record_id==='late-log').occurrence_date,null);assert(model.some(r=>r.kind==='habit'&&r.source_id==='ended'&&r.status==='skipped'));
 await p.screenshot({path:'test-results/all-views/month.png'});
 // 2026-10-10 개편 반영: 옛 목록·보드·표시 일수 화면이 없어져 같은 검증을 주 타임라인·주간 보드·데이터 모델로 옮김
 const weekView=async sub=>{await p.locator('#allViewTabs [data-common-view=week]').click();if(await p.evaluate(()=>allViews.prefs().week)!==sub)await p.locator('#allSubTabs [data-all-sub='+sub+']').click();await p.evaluate(()=>allViews.selectDate('2026-10-04'));};
 await weekView('timeline');const day4='#allTimeDays [data-sv-date="2026-10-04"]';
 assert.equal(await p.locator('#allTimeDays .sv-day').count(),7,'주 = 7일');
 assert.equal(await p.locator(day4+' [data-event-id="event|midnight"]').count(),0,'00시에 끝나는 일정은 다음 날에 안 그림');assert.equal(await p.locator(day4+' [data-event-id="todo|night"]').count(),1);
 const geo=await p.locator(day4+' .ag-tl-content [data-event-id]').evaluateAll(es=>es.filter(e=>['event|same','todo|same'].includes(e.dataset.eventId)).map(e=>({left:e.style.left,color:getComputedStyle(e).backgroundColor})));assert.equal(geo.length,2);assert.notEqual(geo[0].left,geo[1].left);assert.notEqual(geo[0].color,geo[1].color);
 await p.screenshot({path:'test-results/all-views/week-timeline.png'});
 // 날짜 없는 할일·담아두기·습관 원본은 통합 화면 항목이 아님(습관은 회차만)
 assert(!model.some(r=>/someday/.test(r.id)));assert(!model.some(r=>r.kind==='habit'&&!r.action_date&&!r.record_id&&!r.occurrence_date&&r.status==null),'habit rows are occurrences');
 // 모두 끄면 안내, 쓰기 없음, 다른 탭 설정 불변
 const nativeSettings=await p.evaluate(()=>[localStorage.getItem('tok_schedule_views:test'),localStorage.getItem('tok_todos_views:test'),localStorage.getItem('tok_habits_views:test')]);
 await weekView('board');const pressed=async l=>(await l.getAttribute('aria-pressed'))==='true',offAll=async()=>{for(const k of ['todo','habit']){const b=p.locator('#allSidebarTypes [data-aft-eye='+k+']');if(await pressed(b))await b.click();}for(const b of await p.locator('#allSidebarTypes [data-aft-cat^="event|"]').all())if(await pressed(b))await b.click();};
 await offAll();assert.match(await p.locator('#allNotice').textContent(),/표시할 항목이 꺼져 있어요/);assert.equal(await p.locator('#allWeekBoard [data-awb-id]').count(),0);assert.equal(await writes(),0);
 assert.deepEqual(await p.evaluate(()=>[localStorage.getItem('tok_schedule_views:test'),localStorage.getItem('tok_todos_views:test'),localStorage.getItem('tok_habits_views:test')]),nativeSettings);await p.locator('#allShowAll').click();
 // 완료 실패 → 체크 원래대로, 쓰기 없음
 const todoCheck=id=>p.locator('#allWeekBoard [data-awb-id="'+id+'"] .ag-todo-check').first();
 await p.evaluate(()=>mockFailure='completion failed');await todoCheck('todo|same').evaluate(e=>e.click());await p.waitForTimeout(200);assert(!(await todoCheck('todo|same').isChecked()),'실패하면 체크 해제 상태로');assert.equal(await writes(),0);
 // Completion branches use native IDs even when all three kinds have the same ID.
 await todoCheck('todo|same').check();await p.waitForFunction(()=>mockRows.tok_todos.find(r=>r.id==='same').is_done);assert.equal(await p.evaluate(()=>mockRows.tok_events.find(r=>r.id==='same').is_done),undefined);await todoCheck('todo|same').uncheck();await p.waitForFunction(()=>!mockRows.tok_todos.find(r=>r.id==='same').is_done);
 await todoCheck('todo|night').check();await p.waitForFunction(()=>mockRows.tok_todos.some(r=>r.repeat_source_id==='night'));const next=await p.evaluate(()=>mockRows.tok_todos.find(r=>r.repeat_source_id==='night'));assert.equal(next.occurrence_end_date,'2026-10-05');assert.equal(next.end_date,'2026-10-31');assert.equal(next.group_id,'samegroup');assert.equal(next.tag_id,'c');assert.equal(next.project_id,'p');
 // 습관 회차: 체크 = 완료(그 회차 날짜), 해제, ⋯ 메뉴 건너뛰기·취소
 const habitRow=()=>p.locator('#allWeekBoard [data-awb-id^="habit|same|"][data-awb-date="2026-10-03"]').first();
 await habitRow().locator('.ag-habit-check').check();await p.waitForFunction(()=>mockRows.tok_habit_logs.some(r=>r.habit_id==='same'));assert.equal(await p.evaluate(()=>mockRows.tok_habit_logs.filter(r=>r.habit_id==='same').length),1);assert.equal(await p.evaluate(()=>mockRows.tok_habit_logs.find(r=>r.habit_id==='same').done_date),'2026-10-03');
 await p.waitForTimeout(150);await habitRow().locator('.ag-habit-check').uncheck();await p.waitForFunction(()=>!mockRows.tok_habit_logs.some(r=>r.habit_id==='same'));
 await p.waitForTimeout(150);await habitRow().locator('.item-more').click();await p.getByRole('menuitem',{name:'이번만 건너뛰기',exact:true}).click();await p.waitForFunction(()=>mockRows.tok_habit_skips.some(r=>r.habit_id==='same'));
 await p.waitForTimeout(150);await habitRow().locator('.item-more').click();await p.getByRole('menuitem',{name:'건너뛰기 취소',exact:true}).click();await p.waitForFunction(()=>!mockRows.tok_habit_skips.some(r=>r.habit_id==='same'));
 await p.evaluate(()=>allViews.selectDate('2026-10-05')); // 주는 월~일이라 10/5 회차는 다음 주
 assert(await p.evaluate(()=>{const r=allViews.displayRows().find(r=>r.id==='habit|same|planned|2026-10-05');return r.predicted&&r.block===habitStatusBlockReason(tasks.find(h=>h.id==='same'),'2026-10-05');}),'future follows native restrictions');await p.evaluate(()=>allViews.selectDate('2026-10-04'));
 const before=await writes(),source=await p.evaluate(()=>JSON.stringify(mockRows.tok_events.find(r=>r.id==='same')));
 await p.evaluate(async()=>{mockFailure='isolated error';const r=allViews.displayRows().find(r=>r.id==='event|same');await allViews.save(r,{...OnekanPeriod.read('event',r),startDate:'2026-10-05',endDate:'2026-10-05'},'move');});assert.equal(await p.evaluate(()=>JSON.stringify(mockRows.tok_events.find(r=>r.id==='same'))),source);assert.equal(await writes(),before);
 await p.evaluate(async()=>{const r=allViews.displayRows().find(r=>r.id==='event|same'),value={...OnekanPeriod.read('event',r),startDate:'2026-10-05',endDate:'2026-10-05'};await Promise.all([allViews.save(r,value,'move'),allViews.save(r,value,'move')]);});assert.equal(await writes(),before+1);assert.equal(await p.evaluate(()=>mockRows.tok_events.find(r=>r.id==='same').duration_minutes),61);assert.equal(await p.evaluate(()=>mockRows.tok_todos.find(r=>r.id==='same').start_date),'2026-10-04');
 // Kind chooser forwards inclusive and timed contexts to native forms without writes.
 // Kind chooser forwards inclusive and timed contexts to native forms without writes. (주 타임라인의 10/4 열)
 await weekView('timeline');
 const point=async(minute,fraction=.98)=>{const axis=p.locator('#allTimeDays [data-time-date="2026-10-04"]');await axis.locator('..').locator('[data-minute="'+Math.floor(minute/30)*30+'"]').scrollIntoViewIfNeeded();return axis.evaluate((e,[m,f])=>({x:e.getBoundingClientRect().left+e.getBoundingClientRect().width*f,y:e.getBoundingClientRect().top+(m-Number(e.dataset.minMinute))*Number(e.dataset.timeScale)}),[minute,fraction]);};
 const gesture=async(a,b,cancel=false)=>{await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:8});if(cancel)await p.keyboard.press('Escape');await p.mouse.up();};
 let a=await point(660),b=await point(690);a=await point(660);let count=await writes();await gesture(a,b);await p.getByRole('menuitem',{name:'할일 추가',exact:true}).click();assert.equal(await p.locator('#td_time').inputValue(),'11:00');assert.equal(await p.locator('#td_endtime').inputValue(),'11:30');assert.equal(await p.locator('#td_group_id').inputValue(),'');await p.evaluate(()=>closeTodoSheet());assert.equal(await writes(),count);
 a=await point(660);b=await point(690);a=await point(660);await gesture(a,b,true);assert(await p.locator('#allDragPreview').isHidden());assert.equal(await writes(),count);
 // Ordinary todo gestures write its native table/ID; same-ID event and classification stay intact.
 a=await point(585,.3);b=await point(645,.3);a=await point(585,.3);await gesture(a,b);await p.waitForFunction(()=>mockRows.tok_todos.find(r=>r.id==='same').todo_time==='10:30:00');assert.equal(await p.evaluate(()=>mockRows.tok_events.find(r=>r.id==='same').event_time),'09:07:00');
 const handle=p.locator('#allTimeDays [data-event-id="todo|same"] [data-sv-resize]');await handle.scrollIntoViewIfNeeded();await p.locator('#allTimeScroll').evaluate(e=>e.scrollTop+=90);const hr=await handle.boundingBox();b=await p.locator('#allTimeDays [data-time-date="2026-10-04"]').evaluate(e=>({y:e.getBoundingClientRect().top+(720-Number(e.dataset.minMinute))*Number(e.dataset.timeScale)}));await gesture({x:hr.x+4,y:hr.y+3},{x:hr.x+4,y:b.y});await p.waitForFunction(()=>mockRows.tok_todos.find(r=>r.id==='same').end_time==='12:00:00');const movedTodo=await p.evaluate(()=>mockRows.tok_todos.find(r=>r.id==='same'));assert.equal(movedTodo.duration_minutes,90);assert.equal(movedTodo.group_id,'samegroup');assert.equal(movedTodo.tag_id,'c');assert.equal(movedTodo.project_id,'p');assert.equal(movedTodo.is_done,false);count=await writes();
 for(const value of ['event|legacy','todo|night','habit|same|planned|2026-10-03'])await p.evaluate(async value=>{const r=allViews.displayRows().find(r=>r.id===value);if(r)await allViews.save(r,{...OnekanPeriod.read(r.kind,r),startDate:'2026-10-05',endDate:'2026-10-06'},'move');},value);assert.equal(await writes(),count);await p.evaluate(()=>closeHabitSheet());
 await weekView('board');const late=p.locator('#allWeekBoard [data-awb-id="habit|late|planned|2026-10-01"]');assert(await late.count());await late.locator('.item-more').first().click();assert.equal(await p.getByRole('menuitem',{name:'완료로 표시',exact:true}).count(),0,'blocked occurrence menu cannot bypass check guard');await p.keyboard.press('Escape');
 for(const [kind,prefix] of [['event','cev'],['todo','td'],['habit','ha']]){await p.locator('#allAddBtn').click();await p.getByRole('menuitem',{name:({event:'일정',todo:'할일',habit:'습관'})[kind]+' 추가',exact:true}).click();assert(await p.locator('#'+prefix+'_allday').isChecked());await p.evaluate(k=>k==='event'?hideCalEventSheet():k==='todo'?closeTodoSheet():closeHabitAddSheet(),kind);}assert.equal(await writes(),count);
 const prefs=await p.evaluate(()=>localStorage.getItem('tok_all_views:test'));await p.evaluate(()=>{appSymbolUserId='other';allViews.bind();});assert.equal(await p.evaluate(()=>allViews.state().span),'month');await p.evaluate(()=>{appSymbolUserId='test';allViews.bind();});assert.equal(await p.evaluate(()=>localStorage.getItem('tok_all_views:test')),prefs);
 await weekView('timeline');for(const [width,height,theme] of [[1440,900,'white'],[1366,768,'black'],[390,844,'cheese'],[760,768,'white'],[761,768,'white']]){await p.setViewportSize({width,height});await p.evaluate(t=>applyTheme(t),theme);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'test-results/all-views/'+width+'-'+theme+'.png'});}
 assert.deepEqual(await p.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);}),[]);assert.deepEqual(errors,[]);console.log('PASS all: native composite identity, shared lanes (week timeline), snapshot/occurrence branches, all-off notice, completion failure restore, repeat completion, habit done/skip, dedup, guards, native writes, chooser, cancel, mobile/themes');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
