const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:900},timezoneId:'Asia/Seoul'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.setFixedTime(new Date('2026-10-04T03:00:00Z'));await fixture(p);fs.mkdirSync('test-results/calendar-ui',{recursive:true});
 await p.evaluate(async()=>{const period={allDay:false,startDate:'2026-10-04',endDate:'2026-10-04',startTime:'09:07',endTime:'10:08'};mockRows.tok_events=[{id:'e',user_id:'test',title:'긴 제목 일정 · 실제 시간 유지',...OnekanPeriod.patch('event',period)}];mockRows.tok_todos=[{id:'t',user_id:'test',title:'긴 제목 할일 · 실제 시간 유지',...OnekanPeriod.patch('todo',period)}];mockRows.tok_habits=[{id:'h',user_id:'test',name:'긴 제목 습관 · 실제 시간 유지',is_active:true,start_date:'2026-10-04',...OnekanPeriod.patch('habit',period)}];mockRows.tok_time_blocks=[{id:'block',name:'오전',start_minute:540,end_minute:720}];await loadAll();mockWrites.length=0;});
 // 2026-10-10 공용 달력 = 월/주/일 탭(일 = 지금 한칸 타임라인, 주 = 7일). 옛 '표시 일수 1~7'·숨은 기간 버튼 검증을 현재 화면으로 옮김.
 const cases=[['todos','todo','todoViews','todoTopTabs'],['habits','habit','habitViews','habitViewTabs'],['all','all','allViews','allViewTabs']],structure=[];
 for(const [page,prefix,engine,tabs] of cases){
  const cview=v=>p.locator('#'+tabs+' [data-common-view='+v+']').click();
  await p.evaluate(([page,engine])=>{showPage(page);eval(engine).option('mode','calendar');eval(engine).selectDate('2026-10-04');},[page,engine]);
  await cview('week');if(page==='all'&&await p.evaluate(()=>allViews.prefs().week)!=='timeline')await p.locator('#allSubTabs [data-all-sub=timeline]').click();
  const r0=await p.evaluate(e=>eval(e).range(),engine);const dates=await p.locator('#'+prefix+'TimeDays .sv-day').evaluateAll(es=>es.map(e=>e.dataset.svDate));
  assert.equal(dates.length,7);assert.equal(dates[0],r0.start);assert.equal(dates[6],r0.end);assert(dates.includes('2026-10-04'));
  await p.locator('#'+prefix+'NextBtn').click();assert.equal(await p.evaluate(e=>eval(e).range().start,engine),await p.evaluate(d=>addDaysStr(d,7),r0.start),'다음 = 7일 뒤');await p.locator('#'+prefix+'PrevBtn').click();assert.equal(await p.evaluate(e=>eval(e).range().start,engine),r0.start);
  const axes=await p.locator('#'+prefix+'TimeDays [data-time-date]').evaluateAll(es=>es.map(e=>({min:e.dataset.minMinute,scale:e.dataset.timeScale,height:e.style.height,y:e.getBoundingClientRect().top})));assert.equal(axes.length,7);assert(axes.every(a=>a.min===axes[0].min&&a.scale===axes[0].scale&&a.height===axes[0].height&&Math.abs(a.y-axes[0].y)<1));assert.equal(Number(axes[0].scale),9/15);
  structure.push(await p.evaluate(page=>{const host=document.querySelector('.page[data-page='+page+']'),vis=e=>!!e&&!!e.getClientRects().length;return [[...host.querySelectorAll('[data-common-view]')].filter(vis).map(b=>b.dataset.commonView).join(','),vis(host.querySelector('.iv-date-nav'))];},page)); // 화면마다 위쪽 배치는 다르지만(할일 탭 줄·통합 화면 도구 줄) 월/주/일과 날짜 이동은 모두 같음
  await p.screenshot({path:'test-results/calendar-ui/'+page+'-week.png'});
  await cview('month');assert.equal(await p.locator('#'+prefix+'MonthLabel').textContent(),'2026년 10월');assert(await p.locator('.page[data-page='+page+'] .cal-cell.selected').count());assert(await p.locator('.page[data-page='+page+'] .cal-cell.today').count());await p.screenshot({path:'test-results/calendar-ui/'+page+'-month.png'});
  await cview('day');assert.equal(await p.locator('#'+(page==='all'?'allHomeDay':page+'HomeDay')+' .home2-tabpanel:visible').count(),1,'일 = 지금 한칸 화면');
  await cview('week');assert.equal(await p.evaluate(e=>eval(e).state().days,engine),7,'주 복원');
  // 저장된 옛 설정 이전: 여러 날(span 'four')은 주(7일)로, 잘못된 값은 기본(월)으로. 화면·사용자별로 따로.
  await p.evaluate(([page,engine])=>{const key='tok_'+page+'_views:legacy';localStorage.setItem(key,JSON.stringify({span:'four',format:'blocks',date:'2026-10-04',mode:'calendar'}));appSymbolUserId='legacy';eval(engine).bind();},[page,engine]);assert.equal(await p.evaluate(engine=>eval(engine).state().days,engine),7);assert.equal(await p.evaluate(engine=>eval(engine).state().span,engine),'day');
  await p.evaluate(([page,engine])=>{localStorage.setItem('tok_'+page+'_views:invalid',JSON.stringify({span:'wrong',days:99,format:'invalid'}));appSymbolUserId='invalid';eval(engine).bind();},[page,engine]);assert.equal(await p.evaluate(engine=>eval(engine).state().days,engine),1);assert.equal(await p.evaluate(engine=>eval(engine).state().span,engine),'month');
  await p.evaluate(engine=>{appSymbolUserId='test';eval(engine).bind();},engine);assert.equal(await p.evaluate(e=>eval(e).state().days,engine),7,'원래 사용자 설정 유지');
  for(const [width,height,theme] of [[1366,768,'black'],[390,844,'cheese'],[760,768,'white'],[761,768,'white']]){await p.setViewportSize({width,height});await p.evaluate(t=>applyTheme(t),theme);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'test-results/calendar-ui/'+page+'-'+width+'.png'});}await p.setViewportSize({width:1440,height:900});
 }
 assert(structure.every(x=>x[0].startsWith('month,week,day')&&x[1]===true),'세 화면 모두 월/주/일 + 날짜 이동 '+JSON.stringify(structure));
 // A display change or viewport change cancels an actual unfinished drag, without a write. (통합 화면 주 타임라인)
 const allWeek=async()=>{await p.evaluate(()=>{showPage('all');allViews.selectDate('2026-10-04');});await p.locator('#allViewTabs [data-common-view=week]').click();if(await p.evaluate(()=>allViews.prefs().week)!=='timeline')await p.locator('#allSubTabs [data-all-sub=timeline]').click();};
 await allWeek();const axis=p.locator('#allTimeDays [data-time-date="2026-10-04"]');await axis.locator('..').locator('[data-minute="660"]').scrollIntoViewIfNeeded();
 for(const cancel of ['view','width','type','page']){await allWeek();const xy=await axis.evaluate(e=>({x:e.getBoundingClientRect().right-12,y:e.getBoundingClientRect().top+(660-Number(e.dataset.minMinute))*Number(e.dataset.timeScale)}));
  await p.mouse.move(xy.x,xy.y);await p.mouse.down();await p.mouse.move(xy.x,xy.y+25,{steps:6});assert(await p.locator('#allDragPreview').isVisible(),'끌기 미리보기 '+cancel);
  if(cancel==='view')await p.evaluate(()=>allViews.option('span','month'));else if(cancel==='width')await p.setViewportSize({width:1366,height:768});else if(cancel==='type')await p.evaluate(()=>allViews.option('show_event',false));else await p.evaluate(()=>showPage('home'));
  await p.mouse.up();assert(await p.locator('#allDragPreview').isHidden(),'취소 '+cancel);await p.setViewportSize({width:1440,height:900});}
 await p.evaluate(()=>{showPage('home');renderHome();});await p.locator('[data-col2tab=timeline]').click();await p.screenshot({path:'test-results/calendar-ui/home-timeline.png'});await p.locator('[data-col2tab=block]').click();await p.screenshot({path:'test-results/calendar-ui/home-blocks.png'});
 assert.equal(await p.evaluate(()=>mockWrites.length),0);assert.deepEqual(errors,[]);console.log('PASS common UI: three adapters (week 7 days/navigation, aligned axes, month, day = home timeline), legacy/invalid preference migration, page/user isolation, responsive/theme, gesture cancellation, home untouched, no writes/errors');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
