const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:900},timezoneId:'Asia/Seoul'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.setFixedTime(new Date('2026-10-04T03:00:00Z'));await fixture(p);fs.mkdirSync('test-results/calendar-ui',{recursive:true});
 await p.evaluate(async()=>{const period={allDay:false,startDate:'2026-10-04',endDate:'2026-10-04',startTime:'09:07',endTime:'10:08'};mockRows.tok_events=[{id:'e',user_id:'test',title:'긴 제목 일정 · 실제 시간 유지',...OnekanPeriod.patch('event',period)}];mockRows.tok_todos=[{id:'t',user_id:'test',title:'긴 제목 할일 · 실제 시간 유지',...OnekanPeriod.patch('todo',period)}];mockRows.tok_habits=[{id:'h',user_id:'test',name:'긴 제목 습관 · 실제 시간 유지',is_active:true,start_date:'2026-10-04',...OnekanPeriod.patch('habit',period)}];mockRows.tok_time_blocks=[{id:'block',name:'오전',start_minute:540,end_minute:720}];await loadAll();mockWrites.length=0;});
 const cases=[['schedule','schedule','scheduleViews'],['todos','todo','todoViews'],['habits','habit','habitViews'],['all','all','allViews']],structure=[];
 for(const [page,prefix,engine] of cases){
  await p.evaluate(([page,engine])=>{showPage(page);eval(engine).option('mode','calendar');if(page==='schedule'){calSelected='2026-10-04';calCursor='2026-10-01';renderScheduleCalendar();}else eval(engine).selectDate('2026-10-04');},[page,engine]);
  await p.locator('#'+prefix+'CalendarOptions [data-sv-span=day]').click();
  for(let n=1;n<=7;n++){
   await p.locator('#'+prefix+'DayCount').selectOption(String(n));const dates=await p.locator('#'+prefix+'TimeDays .sv-day').evaluateAll(es=>es.map(e=>e.dataset.svDate));assert.deepEqual(dates,Array.from({length:n},(_,i)=>'2026-10-'+String(4+i).padStart(2,'0')));
   const next=prefix==='schedule'?'calNextBtn':prefix+'NextBtn',prev=prefix==='schedule'?'calPrevBtn':prefix+'PrevBtn';await p.locator('#'+next).click();assert.equal(await p.locator('#'+prefix+'Anchor').inputValue(),'2026-10-'+String(4+n).padStart(2,'0'));await p.locator('#'+prev).click();assert.equal(await p.locator('#'+prefix+'Anchor').inputValue(),'2026-10-04');
  }
  const axes=await p.locator('#'+prefix+'TimeDays [data-time-date]').evaluateAll(es=>es.map(e=>({min:e.dataset.minMinute,scale:e.dataset.timeScale,height:e.style.height,y:e.getBoundingClientRect().top})));assert.equal(axes.length,7);assert(axes.every(a=>a.min===axes[0].min&&a.scale===axes[0].scale&&a.height===axes[0].height&&Math.abs(a.y-axes[0].y)<1));assert.equal(Number(axes[0].scale),9/15);
  const controls=await p.locator('.page[data-page='+page+'] .iv-controls').evaluate(e=>[...e.children].map(x=>x.classList.contains('iv-view-tabs')?'views':x.classList.contains('iv-date-nav')?'date':x.id.endsWith('CalendarOptions')?'calendar':'collection'));structure.push(controls);
  await p.screenshot({path:'test-results/calendar-ui/'+page+'-seven.png'});
  await p.locator('#'+prefix+'CalendarOptions [data-sv-format=blocks]').click();assert(await p.locator('#'+prefix+'TimeDays .ag-section-head').count());assert(await p.locator('#'+prefix+'TimeDays .ag-section-head').allTextContents().then(ts=>ts.some(t=>t.includes('오전'))));await p.screenshot({path:'test-results/calendar-ui/'+page+'-blocks.png'});
  await p.locator('#'+prefix+'CalendarOptions [data-sv-span=month]').click();assert.equal(await p.locator('#'+(prefix==='schedule'?'calMonthLabel':prefix+'MonthLabel')).textContent(),'2026년 10월');assert(await p.locator('#'+prefix+'DayCountWrap').isHidden());assert(await p.locator('#'+prefix+'TimeFormat').isHidden());assert(await p.locator('.page[data-page='+page+'] .cal-cell.selected').count());assert(await p.locator('.page[data-page='+page+'] .cal-cell.today').count());await p.screenshot({path:'test-results/calendar-ui/'+page+'-month.png'});
  await p.locator('#'+prefix+'CalendarOptions [data-sv-span=day]').click();assert.equal(await p.locator('#'+prefix+'DayCount').inputValue(),'7');assert.equal(await p.evaluate(engine=>eval(engine).state().format,engine),'blocks');
  await p.locator('#'+prefix+'CalendarOptions [data-sv-format=timeline]').click();
  // Preference migration is page/user specific, including malformed values.
  await p.evaluate(([page,engine])=>{const key='tok_'+page+'_views:legacy';localStorage.setItem(key,JSON.stringify({span:'four',format:'blocks',date:'2026-10-04',mode:'calendar'}));appSymbolUserId='legacy';eval(engine).bind();},[page,engine]);assert.equal(await p.evaluate(engine=>eval(engine).state().days,engine),4);assert.equal(await p.evaluate(engine=>eval(engine).state().span,engine),'day');
  await p.evaluate(([page,engine])=>{localStorage.setItem('tok_'+page+'_views:invalid',JSON.stringify({span:'wrong',days:99,format:'invalid'}));appSymbolUserId='invalid';eval(engine).bind();},[page,engine]);assert.equal(await p.evaluate(engine=>eval(engine).state().days,engine),1);assert.equal(await p.evaluate(engine=>eval(engine).state().span,engine),'month');
  await p.evaluate(engine=>{appSymbolUserId='test';eval(engine).bind();},engine);assert.equal(await p.locator('#'+prefix+'DayCount').inputValue(),'7');
  for(const [width,height,theme] of [[1366,768,'black'],[390,844,'cheese'],[760,768,'white'],[761,768,'white']]){await p.setViewportSize({width,height});await p.evaluate(t=>applyTheme(t),theme);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await p.locator('#'+prefix+'TimeScroll').evaluate(e=>e.scrollWidth>e.clientWidth));await p.screenshot({path:'test-results/calendar-ui/'+page+'-'+width+'.png'});}await p.setViewportSize({width:1440,height:900});
 }
 assert(structure.every(x=>JSON.stringify(x)===JSON.stringify(structure[0])));
 // A display change or viewport change cancels an actual unfinished drag, without a write.
 await p.evaluate(()=>{showPage('all');allViews.selectDate('2026-10-04');allViews.option('days',1);});const axis=p.locator('#allTimeDays [data-time-date]');await axis.locator('..').locator('[data-minute="660"]').scrollIntoViewIfNeeded();const xy=await axis.evaluate(e=>({x:e.getBoundingClientRect().right-12,y:e.getBoundingClientRect().top+(660-Number(e.dataset.minMinute))*Number(e.dataset.timeScale)}));
 for(const cancel of ['days','width','type','page']){await p.mouse.move(xy.x,xy.y);await p.mouse.down();await p.mouse.move(xy.x,xy.y+25,{steps:6});assert(await p.locator('#allDragPreview').isVisible());if(cancel==='days'){await p.evaluate(()=>allViews.option('days',2));}else if(cancel==='width'){await p.setViewportSize({width:1366,height:768});}else if(cancel==='type'){await p.evaluate(()=>allViews.option('show_event',false));}else await p.evaluate(()=>showPage('home'));await p.mouse.up();assert(await p.locator('#allDragPreview').isHidden());await p.evaluate(()=>{showPage('all');allViews.option('days',1);allViews.option('show_event',true);});await p.setViewportSize({width:1440,height:900});await axis.locator('..').locator('[data-minute="660"]').scrollIntoViewIfNeeded();}
 await p.evaluate(()=>{showPage('home');renderHome();});await p.locator('[data-col2tab=timeline]').click();await p.screenshot({path:'test-results/calendar-ui/home-timeline.png'});await p.locator('[data-col2tab=block]').click();await p.screenshot({path:'test-results/calendar-ui/home-blocks.png'});
 assert.equal(await p.evaluate(()=>mockWrites.length),0);assert.deepEqual(errors,[]);console.log('PASS common UI: four adapters, all 1–7 ranges/navigation, aligned axes, month/day restore, old four migration, invalid defaults, page/user isolation, responsive/theme, gesture cancellation, home untouched, no writes/errors');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
