// Synthetic user data. All external requests blocked by the shared fixture.
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./home-layout.cjs');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 try{
 const p=await browser.newPage({viewport:{width:1366,height:768},timezoneId:'Asia/Seoul'}),errors=[],consoleErrors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource|net::ERR_FAILED/.test(m.text()))consoleErrors.push(m.text());});await fixture(p);
 await p.evaluate(async()=>{
  const day=todayStr();mockRows.tok_habit_categories=[{id:'c1',name:'운동',color:'#123456',sort_order:2},{id:'c2',name:'행정',color:'#345678',sort_order:3},{id:'ca',name:'보관 범주',color:'#777777',sort_order:4,is_archived:true}];
  mockRows.tok_event_categories=[{id:'g1',name:'운동',color:'#654321',sort_order:0},{id:'g2',name:'회사',color:'#224466',sort_order:1},{id:'ga',name:'이전 그룹',color:'#999999',is_archived:true,sort_order:2}];
  mockRows.tok_item_groups=[{id:'tg1',kind:'todo',name:'회사',color:'#876543',sort_order:0},{id:'hg1',kind:'habit',name:'회사',color:'#abcdef',sort_order:1},{id:'tga',kind:'todo',name:'보관 할일 그룹',is_archived:true,sort_order:2},...Array.from({length:18},(_,i)=>({id:'extra'+i,kind:'todo',name:i===0?'아주 긴 이름의 개인 그룹도 좁은 화면에서 잘리지 않도록 확인해요':'빈 그룹 '+i,sort_order:i+3}))];
  mockRows.tok_todos=[{id:'t1',title:'회사 할일',tag_id:'c1',group_id:'tg1',project_id:'p1',start_date:day,todo_time:'23:00',duration_minutes:120,is_done:false},{id:'t0',title:'미지정 할일',start_date:null,is_done:false},{id:'ta',title:'보관 그룹 할일',group_id:'tga',tag_id:'ca',start_date:day,is_done:true}];
  mockRows.tok_someday=[{id:'s1',title:'회사 담아두기',group_id:'tg1',tag_id:'c2',project_id:'p1',is_done:false}];
  mockRows.tok_habits=[{id:'h1',name:'회사 습관',group_id:'hg1',category_id:'c1',start_date:addDaysStr(day,-5),end_date:addDaysStr(day,28),start_minute:1380,duration_minutes:120,repeat_unit:'day',repeat_interval:1,is_active:true,project_id:'p1'},{id:'h0',name:'미지정 습관',start_date:day,is_active:true}];
  mockRows.tok_events=[{id:'e1',title:'이전 분류 일정',category_id:'g1',event_date:day,end_date:addDaysStr(day,2),event_time:'23:00',duration_minutes:120},{id:'e2',title:'공용 범주 일정',category_id:'g2',shared_category_id:'c1',event_date:day},{id:'e0',title:'미지정 일정',event_date:day},{id:'ea',title:'보관 그룹 일정',category_id:'ga',event_date:day}];mockRows.tok_projects=[{id:'p1',name:'기존 목표'}];
  // In-memory transport models errors, capability absence, and exact patch preservation.
  sb.from=table=>{let op='select',values,filters=[],single=false,orders=[];const q=new Proxy({}, {get(_,key){if(key==='then')return async resolve=>{
   if(table==='tok_item_groups'&&window.missingClassification)return resolve({data:null,error:{code:'42P01',message:'not installed'}});
   if(op!=='select'&&window.failNextWrite){window.failNextWrite=false;return resolve({data:null,error:{message:'검증용 저장 실패'}});}
   let rows=(mockRows[table]||[]).filter(r=>filters.every(([k,v])=>Array.isArray(v)?v.includes(r[k]):r[k]===v));
   if(op!=='select'){mockWrites.push({table,op,values});if(op==='update')rows.forEach(r=>Object.assign(r,values));if(op==='delete')mockRows[table]=(mockRows[table]||[]).filter(r=>!rows.includes(r));if(op==='insert'){rows=(Array.isArray(values)?values:[values]).map(v=>({id:'new-'+mockWrites.length,...v}));mockRows[table]||=[];mockRows[table].push(...rows);}}
   rows=rows.slice();for(const field of orders.reverse())rows.sort((a,b)=>typeof a[field]==='number'?a[field]-b[field]:String(a[field]||'').localeCompare(String(b[field]||'')));resolve({data:single?rows[0]||null:rows.map(r=>({...r})),error:null});};return (...args)=>{if(['insert','update','delete','upsert'].includes(key)){op=key;values=args[0];}if(['eq','in'].includes(key))filters.push(args);if(['single','maybeSingle'].includes(key))single=true;if(key==='order')orders.push(args[0]);return q;};}});return q;};
  sb.rpc=async(name,args)=>{if(name==='tok_move_someday_to_todo'){const s=mockRows.tok_someday.find(s=>s.id===args.p_someday_id);if(!s)return {error:{message:'someday_not_found'}};const row={...s,start_date:args.p_date,is_done:false,id:'moved-'+s.id};mockRows.tok_todos.push(row);mockRows.tok_someday=mockRows.tok_someday.filter(x=>x!==s);mockWrites.push({table:name,op:'rpc'});return {data:row};}return {data:null};};
  await loadAll();mockWrites.length=0;
 });
 fs.mkdirSync('test-results',{recursive:true});
 const go=async page=>{if(page==='home')return p.locator('#sidebarHomeNav button').click();if(await p.locator('#dedicatedSidebarNav').isVisible())await p.locator('#sidebarRailToggle').click();await p.locator('#mainSidebarNav [data-page='+page+']').click();};
 const close=()=>p.locator('#classificationManageClose').click();
 const selected=async(kind,id)=>p.locator('#classificationSideHost [data-group-select='+id+']').click();
 await go('schedule');await p.locator('#classificationSideHost [data-group-eye=g1]').click();assert(!(await p.evaluate(()=>calEventsOn(todayStr()).some(e=>e.id==='e1'))));assert.equal(await p.evaluate(()=>classification.state('event').selected),'all');
 await p.locator('#scheduleSidebarNav [data-schedule-mode=list]').click();assert(await p.locator('#scheduleList').textContent().then(s=>s.includes('이전 분류 일정')));await selected('event','g1');assert.equal(await p.evaluate(()=>schedMonthEvents().length),1);assert(await p.locator('#scheduleList').textContent().then(s=>s.includes('이전 분류 일정')));assert.equal(await p.evaluate(()=>mockWrites.length),0);
 await p.evaluate(()=>openEventEditor({mode:'add'}));assert.equal(await p.evaluate(()=>cevCategoryValue()),'g1');assert.equal(await p.locator('#cev_shared_category_id').inputValue(),'');await p.evaluate(()=>hideCalEventSheet());
 await p.evaluate(()=>openEventEditor({mode:'edit',id:'e1'}));await p.locator('#cev_shared_category_id').selectOption('c1');await p.locator('#cev_save').click();await p.locator('#calEventSheetBg').waitFor({state:'hidden'});assert.deepEqual(await p.evaluate(()=>({group:events.find(e=>e.id==='e1').category_id,category:events.find(e=>e.id==='e1').shared_category_id,duration:events.find(e=>e.id==='e1').duration_minutes,end:events.find(e=>e.id==='e1').end_date,color:itemTagColor('event',events.find(e=>e.id==='e1').category_id)})),{group:'g1',category:'c1',duration:120,end:await p.evaluate(()=>addDaysStr(todayStr(),2)),color:'#654321'});
 await p.screenshot({path:'test-results/classification-schedule.png'});
 await go('todos');assert.equal(await p.locator('#classificationSideHost [data-group-eye]').count(),20);await selected('todo','tg1');assert.deepEqual(await p.locator('#todoUnifiedList .sv-card').evaluateAll(es=>[...new Set(es.map(e=>e.dataset.id))].sort()),['t1']);
 await p.locator('#todoQuickAddBtn').click();assert.equal(await p.locator('#td_group_id').inputValue(),'tg1');await p.locator('#td_title').fill('새 회사 할일');await p.locator('#td_tag').selectOption('c2');await p.locator('#todoSaveBtn').click();await p.locator('#todoSheetBg').waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>todos.find(t=>t.title==='새 회사 할일').group_id),'tg1');
 await selected('todo','none');await p.locator('#todoQuickAddBtn').click();assert.equal(await p.locator('#td_group_id').inputValue(),'');await p.locator('#todoCancelBtn').click();await selected('todo','extra1');assert.equal(await p.locator('#todoUnifiedList .sv-card').count(),0);
 await selected('todo','all');await p.evaluate(()=>openTodoSheet(todos.find(t=>t.id==='t1')));await p.locator('#td_title').fill('회사 제목만 수정');await p.locator('#todoSaveBtn').click();await p.locator('#todoSheetBg').waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>todos.find(t=>t.id==='t1').duration_minutes),120);assert.equal(await p.evaluate(()=>todos.find(t=>t.id==='t1').project_id),'p1');
 await p.locator('#classificationSideHost [data-add-group]').click();await p.locator('#classificationManageName').fill('공부');await p.locator('#classificationManageColor').fill('#987654');await p.evaluate(()=>window.failNextWrite=true);await p.locator('#classificationManageSave').click();await p.waitForFunction(()=>document.getElementById('classificationManageError').textContent.includes('실패'));assert.equal(await p.locator('#classificationManageName').inputValue(),'공부');await p.locator('#classificationManageSave').click();await p.locator('#classificationManageBg').waitFor({state:'hidden'});
 const newGroup=await p.evaluate(()=>classification.groups().find(g=>g.name==='공부').id);await p.locator('#classificationSideHost [data-group-edit='+newGroup+']').click();await p.getByRole('menuitem',{name:'이름·색상 수정',exact:true}).click();await p.locator('#classificationManageName').fill('개인 공부');await p.locator('#classificationManageSave').click();await p.locator('#classificationManageBg').waitFor({state:'hidden'});
 await p.locator('#classificationSideHost [data-group-edit='+newGroup+']').click();await p.getByRole('menuitem',{name:'그룹 보관',exact:true}).click();await p.waitForFunction(id=>classification.groups().find(g=>g.id===id).is_archived,newGroup);await p.locator('#classificationSideHost [data-archived]').click();assert(await p.locator('#classificationSideHost [data-group-select='+newGroup+']').isVisible());await p.locator('#classificationSideHost [data-group-edit='+newGroup+']').click();await p.getByRole('menuitem',{name:'그룹 복원',exact:true}).click();await p.waitForFunction(id=>!classification.groups().find(g=>g.id===id).is_archived,newGroup);await p.locator('#classificationSideHost [data-archived]').click();
 await p.locator('#classificationSideHost [data-manage-categories]').click();assert.equal(await p.locator('#classificationManageList .hs-cat-purge').count(),0);await p.locator('#classificationManageList .hs-cat-name-input[data-id=c1]').fill('활동');await p.locator('#classificationManageName').focus();await p.waitForFunction(()=>habitCategories.find(c=>c.id==='c1').name==='활동');
 await p.locator('#classificationManageName').fill('창작');await p.locator('#classificationManageSave').click();await p.waitForFunction(()=>habitCategories.some(c=>c.name==='창작'));await p.locator('#classificationManageList .hs-cat-archive[data-id=c2]').click();await p.locator('#classificationManageList [data-catview=archived]').click();assert.equal(await p.locator('#classificationManageList .hs-cat-purge').count(),0);await p.locator('#classificationManageList .hs-cat-unarchive[data-id=c2]').click();await p.locator('#classificationManageList [data-catview=active]').click();
 const orderBefore=await p.evaluate(()=>habitCategories.filter(c=>!c.is_archived).map(c=>c.id));
 const first=p.locator('#classificationManageList .hs-cat-row[data-id='+orderBefore[0]+'] .drag-handle-dots'),last=p.locator('#classificationManageList .hs-cat-row[data-id='+orderBefore.at(-1)+']');
 const from=await first.boundingBox(),to=await last.boundingBox();await p.mouse.move(from.x+from.width/2,from.y+from.height/2);await p.mouse.down();await p.mouse.move(from.x+from.width/2,to.y+to.height-2,{steps:8});await p.mouse.up();
 await p.waitForFunction(first=>habitCategories.filter(c=>!c.is_archived).at(-1).id===first,orderBefore[0]);assert(await p.evaluate(()=>mockWrites.some(w=>w.table==='tok_habit_categories'&&w.op==='update'&&'sort_order' in w.values)));await close();
 await p.screenshot({path:'test-results/classification-todos.png'});
 await go('habits');await selected('habit','hg1');assert.equal(await p.locator('#todoList .todo-row').count(),1);await p.locator('#habitAddBtn').click();assert.equal(await p.locator('#ha_group_id').inputValue(),'hg1');assert.match(await p.locator('#ha_category').textContent(),/활동/);await p.locator('#ha_cancel').click();await p.evaluate(()=>openHabitSheet(tasks.find(h=>h.id==='h1')));assert.equal(await p.locator('#hs_group_id').inputValue(),'hg1');await p.evaluate(()=>closeHabitSheet());
 await go('schedule');await p.evaluate(()=>openEventEditor({mode:'edit',id:'e2'}));assert.match(await p.locator('#cev_shared_category_id').textContent(),/활동/);assert.equal(await p.locator('#cev_shared_category_id').inputValue(),'c1');await p.evaluate(()=>hideCalEventSheet());
 // Clone/repeat/date movement retain independent connections and project IDs.
 await p.evaluate(async()=>{await duplicateAgendaItem('todo','t1');await duplicateAgendaItem('habit','h1');await duplicateAgendaItem('event','e1');});assert(await p.evaluate(()=>todos.some(t=>t.title.includes('(사본)')&&t.group_id==='tg1'&&t.tag_id==='c1'&&t.project_id==='p1')));assert(await p.evaluate(()=>tasks.some(t=>t.name.includes('(사본)')&&t.group_id==='hg1')));assert(await p.evaluate(()=>events.some(e=>e.title.includes('(사본)')&&e.category_id==='g1'&&e.shared_category_id==='c1')));
 await p.evaluate(async()=>{const t=todos.find(t=>t.id==='t1');t.repeat_unit='day';t.repeat_interval=1;await completeTodoRepeatIfNeeded(t);});assert(await p.evaluate(()=>mockRows.tok_todos.some(t=>t.repeat_source_id==='t1'&&t.group_id==='tg1'&&t.tag_id==='c1'&&t.project_id==='p1')));
 await p.evaluate(async()=>{await moveItemToZone('todo','t1',{zone:'planday',date:addDaysStr(todayStr(),1)});await moveItemToZone('someday','s1',{zone:'today-allday',date:todayStr()});});assert(await p.evaluate(()=>todos.some(t=>t.title==='회사 담아두기'&&t.group_id==='tg1'&&t.tag_id==='c2'&&t.project_id==='p1')));
 await p.evaluate(async()=>{await moveItemToZone('todo','t1',{zone:'someday'});});assert(await p.evaluate(()=>somedayItems.some(t=>t.group_id==='tg1'&&t.tag_id==='c1'&&t.project_id==='p1')));
 for(const [width,height] of [[1366,768],[1440,320],[390,844],[760,768],[761,768]]){await p.setViewportSize({width,height});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.evaluate(()=>openEventEditor({mode:'edit',id:'e1'}));assert.equal(await p.locator('#cev_shared_category_id').inputValue(),'c1');await p.evaluate(()=>hideCalEventSheet());}
 await p.setViewportSize({width:390,height:844});await p.locator('[data-classification-mobile=schedule] button').nth(0).click();assert(await p.locator('#classificationManageList').isVisible());await p.screenshot({path:'test-results/classification-mobile-groups.png'});await close();await p.locator('[data-classification-mobile=schedule] button').nth(1).click();await p.locator('#classificationManageList [data-catview=active]').click();await p.locator('#classificationManageList .hs-cat-name-input').first().fill('모바일 범주 수정');await p.locator('#classificationManageName').focus();await p.waitForFunction(()=>habitCategories.some(c=>c.name==='모바일 범주 수정'));await p.screenshot({path:'test-results/classification-mobile-categories.png'});await close();
 // Missing migration only disables new capabilities; no silent discard or blocked legacy app.
 await p.evaluate(async()=>{window.missingClassification=true;await loadAll();openEventEditor({mode:'add'});});assert(await p.locator('#cev_shared_category_id').isDisabled());assert.equal(await p.evaluate(()=>classification.isReady()),false);await p.evaluate(()=>hideCalEventSheet());
 await p.evaluate(async()=>{window.missingClassification=false;await loadAll();classification.select('todo','tg1');bindAppSymbolUser('other-user');});assert.equal(await p.evaluate(()=>classification.state('todo').selected),'all');assert.equal(await p.evaluate(()=>classification.groups().length),0);await p.evaluate(()=>{showPage('schedule');classification.render();});assert.equal(await p.locator('#classificationSideHost [data-group-row]').count(),0);
 assert.equal(await p.locator('#settingsTagList,#settingsEventCatList').count(),0);assert.equal(await p.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.children.length===0&&e.textContent.includes('태그')).length),0);assert.deepEqual(await p.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);}),[]);assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);
 console.log('PASS classification UI: legacy colors/links, independent selection/eyes, group/category CRUD and archive, defaults, shared edits, missing migration, account separation, copy/repeat/move, period/project preservation, mobile/breakpoint, no IDs/errors');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
