const fs=require('node:fs'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const A='00000000-0000-0000-0000-000000000001',B='00000000-0000-0000-0000-000000000002';
async function fixture(){
 const db=new PGlite();await db.exec(`create schema auth;create role authenticated;create role anon;create table auth.users(id uuid primary key);insert into auth.users values('${A}'),('${B}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;
 create table tok_habit_categories(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid(),name text not null,color text,sort_order int default 0,is_archived boolean default false,created_at timestamptz default now());
 create table tok_event_categories(like tok_habit_categories including all);
 create table tok_projects(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid(),name text,unique(id,user_id));
 create table tok_events(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid(),title text,event_date date,end_date date,event_time time,duration_minutes int,category_id uuid references tok_event_categories(id) on delete set null);
 create table tok_todos(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid(),title text,start_date date,end_date date,todo_time time,duration_minutes int,is_done boolean default false,tag_id uuid references tok_habit_categories(id) on delete set null,project_id uuid references tok_projects(id),repeat_unit text,repeat_source_id uuid);
 create table tok_habits(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid(),name text,start_date date,end_date date,start_minute int,duration_minutes int default 30,is_active boolean default true,category_id uuid references tok_habit_categories(id) on delete set null,project_id uuid);
 create table tok_someday(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid(),title text,is_done boolean default false,tag_id uuid references tok_habit_categories(id) on delete set null);
 create table tok_habit_logs(id uuid primary key default gen_random_uuid(),habit_id uuid,done_date date,start_minute int,duration_minutes int);
 create table tok_habit_skips(id uuid primary key default gen_random_uuid(),habit_id uuid,skip_date date);
 create table tok_habit_pauses(id uuid primary key default gen_random_uuid(),habit_id uuid,paused_at date,resumed_at date);`);
 for(const table of ['tok_habit_categories','tok_event_categories','tok_projects','tok_events','tok_todos','tok_habits','tok_someday'])await db.exec(`alter table ${table} enable row level security;grant select,insert,update,delete on ${table} to authenticated;create policy ${table}_s on ${table} for select to authenticated using(auth.uid()=user_id);create policy ${table}_i on ${table} for insert to authenticated with check(auth.uid()=user_id);create policy ${table}_u on ${table} for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy ${table}_d on ${table} for delete to authenticated using(auth.uid()=user_id);`);
 const as=(id,sql,params=[])=>db.transaction(async tx=>{await tx.exec(`set local role ${id?'authenticated':'anon'}`);await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[id||'']);return tx.query(sql,params);});
 return {db,as};
}
module.exports={fixture,A,B};
if(require.main===module)(async()=>{
 const {db,as}=await fixture();try{
 const c=(await as(A,"insert into tok_habit_categories(name,color,sort_order,is_archived) values('동일 이름','#123456',5,true) returning id")).rows[0].id;
 const g=(await as(A,"insert into tok_event_categories(name,color,sort_order) values('동일 이름','#654321',7) returning id")).rows[0].id;
 const p=(await as(A,"insert into tok_projects(name) values('기존 목표') returning id")).rows[0].id;
 const e=(await as(A,"insert into tok_events(title,event_date,end_date,event_time,duration_minutes,category_id) values('기존 일정','2026-10-03','2026-10-05','23:00',120,$1) returning id",[g])).rows[0].id;
 const t=(await as(A,"insert into tok_todos(title,start_date,tag_id,project_id,is_done,duration_minutes) values('기존 할일','2026-10-03',$1,$2,true,120) returning id",[c,p])).rows[0].id;
 const h=(await as(A,"insert into tok_habits(name,start_date,end_date,category_id,start_minute,duration_minutes) values('기존 습관','2026-10-03','2026-10-31',$1,1380,120) returning id",[c])).rows[0].id;
 await as(A,"insert into tok_someday(title,tag_id) values('날짜 없음',$1)",[c]);await db.query("insert into tok_habit_logs(habit_id,done_date,start_minute,duration_minutes) values($1,'2026-09-29',1380,120)",[h]);await db.query("insert into tok_habit_skips(habit_id,skip_date) values($1,'2026-09-28')",[h]);await db.query("insert into tok_habit_pauses(habit_id,paused_at,resumed_at) values($1,'2026-09-26','2026-09-27')",[h]);
 const snapshot=async()=>JSON.stringify((await db.query(`select 'events' kind,to_jsonb(i)-'shared_category_id' row from tok_events i union all select 'todos',to_jsonb(i)-'group_id' from tok_todos i union all select 'habits',to_jsonb(i)-'group_id' from tok_habits i union all select 'someday',to_jsonb(i)-'group_id'-'project_id' from tok_someday i union all select 'categories',to_jsonb(i) from tok_habit_categories i union all select 'schedulegroups',to_jsonb(i) from tok_event_categories i union all select 'logs',to_jsonb(i) from tok_habit_logs i union all select 'skips',to_jsonb(i) from tok_habit_skips i union all select 'pauses',to_jsonb(i) from tok_habit_pauses i order by kind,row`)).rows);
 const before=await snapshot(),policies=JSON.stringify((await db.query('select * from pg_policies order by tablename,policyname')).rows);
 await db.exec(fs.readFileSync('supabase/migrations/20261003114452_tok_groups_shared_categories.sql','utf8'));assert.equal(await snapshot(),before);assert.equal(JSON.stringify((await db.query("select * from pg_policies where tablename<>'tok_item_groups' order by tablename,policyname")).rows),policies);
 const tg=(await as(A,"insert into tok_item_groups(kind,name,color) values('todo','회사','#112233') returning id")).rows[0].id,hg=(await as(A,"insert into tok_item_groups(kind,name) values('habit','회사') returning id")).rows[0].id;
 const bc=(await as(B,"insert into tok_habit_categories(name) values('타인 범주') returning id")).rows[0].id,bg=(await as(B,"insert into tok_item_groups(kind,name) values('todo','타인 그룹') returning id")).rows[0].id;
 assert.equal((await as(B,'select * from tok_item_groups where id=$1',[tg])).rows.length,0);await assert.rejects(as(null,'select * from tok_item_groups'));
 for(const [sql,args] of [['update tok_todos set group_id=$1 where id=$2',[hg,t]],['update tok_todos set group_id=$1 where id=$2',[bg,t]],['update tok_todos set tag_id=$1 where id=$2',[bc,t]],['update tok_events set shared_category_id=$1 where id=$2',[bc,e]],['update tok_habits set group_id=$1 where id=$2',[tg,h]],['update tok_item_groups set kind=$1 where id=$2',['habit',tg]],['delete from tok_item_groups where id=$1',[tg]]])await assert.rejects(as(A,sql,args));
 await as(A,'update tok_todos set group_id=$1 where id=$2',[tg,t]);await as(A,'update tok_habits set group_id=$1 where id=$2',[hg,h]);await as(A,'update tok_events set shared_category_id=$1 where id=$2',[c,e]);await as(A,'update tok_item_groups set is_archived=true where id=$1',[tg]);assert.equal((await as(A,'select group_id from tok_todos where id=$1',[t])).rows[0].group_id,tg);await as(A,'update tok_item_groups set is_archived=false where id=$1',[tg]);
 const sd=(await as(A,'insert into tok_someday(title,tag_id,group_id,project_id) values($1,$2,$3,$4) returning id',['이동 보존',c,tg,p])).rows[0].id;
 const moved=(await as(A,'select * from tok_move_someday_to_todo($1,$2)',[sd,'2026-10-04'])).rows[0];assert.equal(moved.tag_id,c);assert.equal(moved.group_id,tg);assert.equal(moved.project_id,p);assert.equal(moved.is_done,false);await assert.rejects(as(A,'select tok_move_someday_to_todo($1,$2)',[sd,'2026-10-04']));
 const foreign=(await as(B,"insert into tok_someday(title) values('타인 이동') returning id")).rows[0].id;await assert.rejects(as(A,'select tok_move_someday_to_todo($1,$2)',[foreign,'2026-10-04']));
 console.log('PASS additive schema: legacy rows/colors/order/connections/history/RLS preserved; owner/kind/anon/delete blocked; archive/restore; atomic movement and project preservation');
 }finally{await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
