const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
fs.mkdirSync('test-results/goals',{recursive:true});
for(const width of [1366,390,760,761]){
const page=await browser.newPage({viewport:{width,height:width<=760?844:768},timezoneId:'Asia/Seoul'}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await fixture(page,process.env.ONEKAN_TEST_SOURCE?fs.readFileSync(process.env.ONEKAN_TEST_SOURCE,'utf8'):undefined);
await page.evaluate(()=>{mockRows.tok_projects=[{id:'p',user_id:'test',name:'그림을 꾸준히 만드는 목표',description:'설명 · 기존 연결 유지',parent_id:null,identity_id:'i',lifecycle_state:'active',is_archived:false},{id:'c',user_id:'test',name:'하위 프로젝트',parent_id:'p',lifecycle_state:'active',is_archived:false},{id:'e',user_id:'test',name:'종료한 목표',parent_id:null,lifecycle_state:'ended',is_archived:false},{id:'a',user_id:'test',name:'보관된 종료 목표',parent_id:null,lifecycle_state:'ended',is_archived:true}];mockRows.tok_identities=[{id:'i',name:'창작하는 사람'}];mockRows.tok_habit_categories=[{id:'tag',name:'창작 범주',color:'#9a78aa'}];mockRows.tok_item_groups=[{id:'g',kind:'todo',name:'개인'}];mockRows.tok_todos=[{id:'t',user_id:'test',title:'자정을 넘는 연결 할일',project_id:'p',start_date:todayStr(),occurrence_end_date:OnekanPeriod.addDays(todayStr(),1),todo_time:'23:00',end_time:'01:00',all_day:false,duration_minutes:120,is_done:false,group_id:'g',tag_id:'tag'},{id:'done',user_id:'test',title:'완료한 직접 할일',project_id:'p',is_done:true},{id:'ct',user_id:'test',title:'하위 할일',project_id:'c',is_done:false},{id:'et',user_id:'test',title:'종료 목표 기존 연결',project_id:'e',is_done:false}];mockRows.tok_habits=[{id:'h',name:'연결된 습관',is_active:true,start_date:todayStr(),repeat_unit:'day',repeat_interval:1,project_id:'p'}];});await page.evaluate(()=>loadAll());await page.evaluate(()=>showPage('work'));
assert(await page.locator('#projectList').isVisible());assert(!(await page.locator('#projectDetail').isVisible()));assert.equal(await page.locator('#projectList [data-proj]').count(),1);assert.equal(await page.locator('#goalMobileState').isVisible(),width<=760);
const selected=await page.locator('#projectList').innerHTML();await page.evaluate(()=>setSidebarMode(false));assert.equal(await page.locator('#projectList').innerHTML(),selected);await page.evaluate(()=>setSidebarMode(true));
await page.locator('#projectList [data-proj=p]').click();assert(!(await page.locator('#projectList').isVisible()));assert(await page.locator('#projectDetail').isVisible());assert.equal(await page.locator('#projectDetail [data-id=ct]').count(),0);assert.equal(await page.locator('#projectDetail [data-kind=habit] input[type=checkbox]').count(),0);assert((await page.locator('#projectDetail').innerText()).includes('직접 연결 미완료 1 / 완료 1'));
await page.locator('#projNewTodoBtn').click();assert.equal(await page.locator('#td_project').inputValue(),'p');assert(await page.locator('#td_allday').isChecked());await page.evaluate(()=>closeTodoSheet());
await page.locator('#projNewHabitBtn').click();assert.equal(await page.locator('#ha_project').inputValue(),'p');assert(await page.locator('#ha_allday').isChecked());await page.evaluate(()=>closeHabitAddSheet());
const external=await page.evaluate(()=>JSON.stringify(mockRows.tok_todos.find(t=>t.id==='et')));
await page.locator('#projLinkTodoBtn').click();await page.locator('#pl_list [data-id=et]').click();assert((await page.locator('#confirmBg').innerText()).includes('종료한 목표'));await page.locator('#confirm_ok').click();await page.waitForFunction(()=>todos.find(t=>t.id==='et').project_id==='p');await page.evaluate(()=>closeProjectLink());
assert.deepEqual(await page.evaluate(()=>{const t={...mockRows.tok_todos.find(t=>t.id==='et')};delete t.project_id;return t;}),(()=>{const t=JSON.parse(external);delete t.project_id;return t;})());
await page.evaluate(()=>setItemProject('todo','et','e')); // Closed goal rejects a new connection; original row remains in active goal.
assert.equal(await page.evaluate(()=>todos.find(t=>t.id==='et').project_id),'p');
await page.evaluate(()=>setItemProject('todo','et',null));
const itemBefore=await page.evaluate(()=>JSON.stringify(mockRows.tok_todos));
await page.locator('[data-goal-action=end]').click();await page.locator('#confirm_ok').click();await page.waitForFunction(()=>projects.find(p=>p.id==='p').lifecycle_state==='ended');assert.equal(await page.evaluate(()=>JSON.stringify(mockRows.tok_todos)),itemBefore);assert(!(await page.locator('#projNewTodoBtn').isVisible()));
await page.locator('[data-goal-action=archive]').click();await page.locator('#confirm_ok').click();await page.waitForFunction(()=>projects.find(p=>p.id==='p').is_archived);assert.equal(await page.evaluate(()=>projectById('c').is_archived),false);
await page.locator('[data-goal-action=restore]').click();await page.locator('#confirm_ok').click();await page.waitForFunction(()=>!projects.find(p=>p.id==='p').is_archived);assert.equal(await page.evaluate(()=>projectById('p').lifecycle_state),'ended');
await page.evaluate(()=>openTodoSheet(todos.find(t=>t.id==='t')));assert.equal(await page.locator('#td_project').inputValue(),'p');assert((await page.locator('#td_project').innerText()).includes('현재 연결'));await page.locator('#td_title').fill('종료 목표 연결을 보존한 제목 수정');await page.locator('#todoSaveBtn').click();await page.waitForFunction(()=>!document.querySelector('#todoSheetBg').classList.contains('open'));assert.equal(await page.evaluate(()=>todos.find(t=>t.id==='t').project_id),'p');
await page.evaluate(()=>{mockFailure='injected failure';});await page.locator('[data-goal-action=resume]').click();await page.locator('#confirm_ok').click();await page.waitForFunction(()=>!goalBusy.size);assert.equal(await page.evaluate(()=>projectById('p').lifecycle_state),'ended');
await page.locator('[data-goal-action=resume]').click();await page.locator('#confirm_ok').click();await page.waitForFunction(()=>projectById('p').lifecycle_state==='active');
await page.evaluate(()=>scrollTo(0,0));
for(const theme of ['white','black','cheese']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.screenshot({path:`test-results/goals/detail-${width}-${theme}.png`,fullPage:true});}
await page.screenshot({path:`test-results/goals/detail-${width}.png`,fullPage:true});
await page.locator('#projBackBtn').click();assert(await page.locator('#projectList').isVisible());
for(const state of ['active','ended','archived']){await page.evaluate(s=>selectGoalState(s),state);assert(!(await page.locator('#projectDetail').isVisible()));await page.screenshot({path:`test-results/goals/${state}-${width}.png`,fullPage:true});}
await page.evaluate(()=>{selectGoalState('ended');selectGoal('e');});assert.equal(await page.locator('#projectDetail .proj-title').innerText(),'종료한 목표');assert(!(await page.locator('#projLinkTodoBtn').isVisible()));
await page.evaluate(()=>{selectGoalState('active');selectGoal('p');});await page.locator('#projectDetail [data-proj=c]').click();await page.locator('#projNewTodoBtn').click();assert.equal(await page.locator('#td_project').inputValue(),'c');await page.evaluate(()=>closeTodoSheet());
await page.evaluate(()=>setItemProject('todo','t',null));assert.equal(await page.evaluate(()=>mockRows.tok_todos.find(x=>x.id==='t').project_id),null);
assert.equal(await page.evaluate(()=>{const t=mockRows.tok_todos.find(x=>x.id==='t');return t.group_id==='g'&&t.tag_id==='tag'&&t.duration_minutes===120;}),true);
await page.evaluate(()=>setItemProject('todo','t','p'));
const n=await page.evaluate(()=>mockWrites.length);for(const kind of ['schedule','todos','habits','all']){await page.evaluate(k=>showPage(k),kind);assert.equal(await page.locator('.iv-controls>.iv-view-tabs:visible').count(),width<=760?1:0);}
assert.equal(await page.evaluate(()=>mockWrites.length),n);assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(n=>n.id);return ids.filter((n,i)=>ids.indexOf(n)!==i);}),[]);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.evaluate(()=>{selectGoalState('active');selectGoal('p');openProjectSheet({mode:'edit',id:'p'});mockFailure='goal save failure';});await page.locator('#pj_name').fill('실패 시 유지할 목표 이름');await page.locator('#pj_save').click();await page.waitForFunction(()=>document.querySelector('#pj_error').textContent.includes('저장하지 못'));assert.equal(await page.locator('#pj_name').inputValue(),'실패 시 유지할 목표 이름');await page.evaluate(()=>closeProjectSheet());
await page.evaluate(async()=>{for(let i=0;i<40;i++)mockRows.tok_projects.push({id:'many'+i,user_id:'test',name:'긴 목표 이름 '+i+' · 많은 목표 조회 스크롤 검증',parent_id:null,lifecycle_state:'active',is_archived:false});await loadAll();showPage('work');selectGoalState('active');scrollTo(0,700);});const scroll=await page.evaluate(()=>scrollY);await page.evaluate(()=>selectGoal('p'));await page.locator('#projBackBtn').click();assert.equal(await page.evaluate(()=>scrollY),scroll);
if(width>760){await page.locator('#pageSidebarItems [data-goal-state=ended]').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>goalState),'ended');}else{await page.locator('#goalMobileState').selectOption('ended');assert.equal(await page.evaluate(()=>goalState),'ended');}
await page.evaluate(()=>{selectGoalState('ended');selectGoal('e');saveGoalPrefs();bindGoalUser('other');});assert.equal(await page.evaluate(()=>workSelectedId),null);assert.equal(await page.evaluate(()=>goalState),'active');await page.evaluate(()=>bindGoalUser('test'));assert.equal(await page.evaluate(()=>workSelectedId),'e');assert.equal(await page.evaluate(()=>goalState),'ended');
await page.evaluate(async()=>{await loadAll();workSelectedId='no-access';renderWork();});assert.equal(await page.evaluate(()=>workSelectedId),null);
await page.close();console.log(width,'PASS independent goal pages, lifecycle/archive/restore, input defaults, inherited links/period, failure, boundary nav/no writes/no duplicate IDs/errors');
}
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
