const fs=require('node:fs'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const A='00000000-0000-0000-0000-000000000001',B='00000000-0000-0000-0000-000000000002';
(async()=>{const db=new PGlite();try{
await db.exec(`create schema auth;create role authenticated;create role anon;create table auth.users(id uuid primary key);insert into auth.users values('${A}'),('${B}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;
create table tok_todos(id uuid primary key default gen_random_uuid(),user_id uuid default auth.uid(),title text,start_date date,end_date date,todo_time time,duration_minutes int,is_done boolean default false,repeat_unit text,repeat_source_id uuid,tag_id uuid,group_id uuid);
create table tok_habits(id uuid primary key default gen_random_uuid(),user_id uuid default auth.uid(),name text,is_active boolean default true,start_date date,end_date date);
create table tok_someday(id uuid primary key default gen_random_uuid(),user_id uuid default auth.uid(),title text,project_id uuid);
create table tok_habit_logs(habit_id uuid,done_date date);create table tok_habit_skips(habit_id uuid,skip_date date);`);
await db.exec(fs.readFileSync('supabase/migrations/20260929000000_tok_projects_identities.sql','utf8'));
for(const t of ['tok_projects','tok_identities','tok_todos','tok_habits','tok_someday']){await db.exec(`grant select,insert,update on ${t} to authenticated;`);if(!['tok_projects','tok_identities'].includes(t))await db.exec(`alter table ${t} enable row level security;create policy own on ${t} for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);`);}
await db.exec('alter table tok_todos add constraint source_unique unique(repeat_source_id);alter table tok_someday add constraint owner_project foreign key(project_id,user_id) references tok_projects(id,user_id);');
const as=(id,sql,args=[])=>db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[id]);return tx.query(sql,args);});
const p=(await as(A,"insert into tok_projects(name,description,sort_order) values('기존 목표','설명',5) returning id")).rows[0].id;
const child=(await as(A,"insert into tok_projects(name,parent_id) values('하위',$1) returning id",[p])).rows[0].id;
const t=(await as(A,"insert into tok_todos(title,start_date,end_date,todo_time,duration_minutes,is_done,repeat_unit,project_id) values('반복','2026-10-03','2026-10-31','23:00',120,true,'day',$1) returning id",[child])).rows[0].id;
const h=(await as(A,"insert into tok_habits(name,project_id) values('습관',$1) returning id",[p])).rows[0].id;await db.query("insert into tok_habit_logs values($1,'2026-10-01')",[h]);await db.query("insert into tok_habit_skips values($1,'2026-10-02')",[h]);
const snapshot=async()=>JSON.stringify((await db.query("select 'todo' kind,to_jsonb(t) row from tok_todos t union all select 'habit',to_jsonb(t) from tok_habits t union all select 'log',to_jsonb(t) from tok_habit_logs t union all select 'skip',to_jsonb(t) from tok_habit_skips t order by kind,row")).rows);
const old=await snapshot(),policies=JSON.stringify((await db.query('select * from pg_policies order by tablename,policyname')).rows);
await db.exec(fs.readFileSync('supabase/migrations/20261004063637_tok_goal_lifecycle.sql','utf8'));
assert.equal(await snapshot(),old);assert.equal(JSON.stringify((await db.query('select * from pg_policies order by tablename,policyname')).rows),policies);
assert.equal((await as(A,'select lifecycle_state,is_archived from tok_projects where id=$1',[p])).rows[0].lifecycle_state,'active');
await as(A,"update tok_projects set lifecycle_state='ended' where id=$1",[p]);await as(A,'update tok_projects set is_archived=true where id=$1',[p]);assert.equal(await snapshot(),old);
await assert.rejects(as(A,"update tok_projects set lifecycle_state='active' where id=$1",[p]),/goal_restore/);
await as(A,'update tok_projects set is_archived=false where id=$1',[p]);assert.equal((await as(A,'select lifecycle_state from tok_projects where id=$1',[p])).rows[0].lifecycle_state,'ended');
await assert.rejects(as(A,"insert into tok_todos(title,project_id) values('新',$1)",[child]),/goal_not_accepting/);
await assert.rejects(as(A,"insert into tok_habits(name,project_id) values('新',$1)",[p]),/goal_not_accepting/);
await assert.rejects(as(A,"insert into tok_projects(name,parent_id) values('子',$1)",[p]),/goal_not_accepting/);
await assert.rejects(as(A,"update tok_projects set lifecycle_state='bogus' where id=$1",[p]));
await assert.rejects(as(A,'update tok_projects set is_archived=true where id=$1',[child]));
await as(A,"update tok_todos set title='제목만',project_id=$1 where id=$2",[child,t]);await as(A,'update tok_habits set is_active=false where id=$1',[h]);
await as(A,"insert into tok_todos(title,start_date,repeat_unit,repeat_source_id,project_id) values('다음','2026-10-04','day',$1,$2)",[t,child]);
await assert.rejects(as(A,"insert into tok_todos(title,start_date,repeat_unit,repeat_source_id,project_id) values('중복','2026-10-04','day',$1,$2)",[t,child]));
assert.equal((await as(B,'select * from tok_projects where id=$1',[p])).rows.length,0);assert.equal((await as(B,"update tok_projects set name='침입' where id=$1 returning id",[p])).rows.length,0);
await assert.rejects(as(B,"insert into tok_habits(name,project_id) values('타인 연결',$1)",[p]),/goal_owner/);
await as(A,"update tok_projects set lifecycle_state='active' where id=$1",[p]);await as(A,'update tok_projects set is_archived=true where id=$1',[p]);await as(A,'update tok_projects set is_archived=false where id=$1',[p]);
await as(A,'update tok_todos set project_id=null where id=$1',[t]);await as(A,'update tok_todos set project_id=$1 where id=$2',[p,t]);
await assert.rejects(as(A,'update tok_projects set parent_id=$1 where id=$2',[child,p]));
console.log('PASS additive migration, lifecycle/archive restore, parent-only changes, legacy connections/period/history, closed-goal new-link rejection, repeating continuation, duplicate/ownership/RLS/depth guards');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
