// Native habit sources and literal snapshots, isolated from every external service.
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await browser.newPage({viewport:{width:1440,height:900},timezoneId:'Asia/Seoul',hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource|net::ERR_FAILED/.test(m.text()))errors.push(m.text());});p.on('dialog',d=>d.accept());await p.clock.setFixedTime(new Date("2026-10-04T03:00:00Z"));await fixture(p);fs.mkdirSync('test-results/habit-views',{recursive:true});
 await p.evaluate(async()=>{
  const all=(a,b)=>OnekanPeriod.patch('habit',{allDay:true,startDate:a,endDate:b}),timed=(a,b,c,d)=>OnekanPeriod.patch('habit',{allDay:false,startDate:a,endDate:b,startTime:c,endTime:d});
  const base={user_id:'test',is_active:true,repeat_unit:'day',repeat_interval:1,start_date:'2026-10-03',end_date:'2026-10-10'};
  mockRows.tok_habits=[
   {...base,id:'night',name:'밤을 넘는 습관',group_id:'g1',category_id:'c1',project_id:'p1',...timed('2026-10-03','2026-10-04','23:00','01:00')},
   {...base,id:'midnight',name:'00시 종료',repeat_unit:null,...timed('2026-10-03','2026-10-04','23:00','00:00')},
   {...base,id:'multi',name:'여러 날 종일',repeat_unit:null,...all('2026-10-03','2026-10-06')},
   {...base,id:'overlap',name:'겹치는 시간과 아주 긴 이름의 습관을 좁은 화면에서도 읽고 조작할 수 있는지 확인합니다',repeat_interval:2,...timed('2026-10-03','2026-10-04','23:30','00:30')},
   {...base,id:'long',name:'여러 날 시간 지정',repeat_unit:null,...timed('2026-10-03','2026-10-06','10:15','12:45')},
   {...base,id:'weekly',name:'요일 습관',repeat_unit:'week',repeat_days:[1,3],...all('2026-10-03','2026-10-03')},
   {...base,id:'paused',name:'재개한 습관',...all('2026-10-03','2026-10-03')},
   {...base,id:'arch',name:'보관된 습관',is_active:false,...all('2026-10-03','2026-10-03')},
   {...base,id:'end',name:'종료된 습관',end_date:'2026-10-02',...all('2026-10-01','2026-10-01')},
   {...base,id:'late',name:'밀린 월간 습관',repeat_unit:'month',start_date:'2026-10-01',...all('2026-10-01','2026-10-01')},
   {...base,id:'legacy',name:'종료 없는 기존 습관',start_minute:780,duration_minutes:null,all_day:null},
   {...base,id:'record',name:'시간을 바꾼 습관',...timed('2026-10-03','2026-10-03','15:00','17:00')}
  ];
  mockRows.tok_habit_logs=[{id:'log1',habit_id:'record',done_date:'2026-10-02',start_minute:1380,duration_minutes:120,occurrence_end_date:'2026-10-03'},{id:'old',habit_id:'record',done_date:'2026-10-01',start_minute:540,duration_minutes:null}];
  mockRows.tok_habit_pauses=[{habit_id:'paused',paused_at:'2026-10-03',resumed_at:'2026-10-06'},{habit_id:'arch',paused_at:'2026-10-04',resumed_at:null}];
  mockRows.tok_item_groups=[{id:'g1',kind:'habit',name:'개인',color:'#718fc5'},{id:'g2',kind:'habit',name:'빈 그룹'},{id:'ga',kind:'habit',name:'보관 그룹',is_archived:true}];mockRows.tok_habit_categories=[{id:'c1',name:'건강',color:'#ad7cb5'}];mockRows.tok_projects=[{id:'p1',name:'기존 목표',is_active:true}];mockRows.tok_time_blocks=[{id:'block',title:'오전',start_minute:540,end_minute:720}];
  await loadAll();habitViews.selectDate('2026-10-04');showPage('habits');mockWrites.length=0;
 });
 const writes=()=>p.evaluate(()=>mockWrites.length),switchTo=m=>p.locator('#habitViewTabs [data-tab='+m+']').click();
 assert.equal(await p.evaluate(()=>habitViews.state().mode),'list');assert.equal(await p.locator('#todoList .todo-row[data-id=night]').count(),1);assert.equal(await p.locator('#todoList .todo-row[data-id=arch]').count(),0);
 assert.deepEqual(await p.locator('#pageSidebarItems button').allTextContents(),['달력','목록','보드']);await p.screenshot({path:'test-results/habit-views/list.png'});
 await p.locator('#habitSort').selectOption('name');for(const group of ['group','category','project','none'])await p.locator('#habitGroup').selectOption(group);
 await switchTo('board');assert.equal(await p.locator('#habitBoard .todo-row[data-id=night]').count(),1);assert(await p.locator('#habitBoard [data-bucket=g2]').count());await p.screenshot({path:'test-results/habit-views/board.png'});for(const b of ['category','project','group'])await p.locator('#habitBoardBy').selectOption(b);
 await p.locator('#classificationSideHost [data-group-eye=g1]').click();assert.equal(await p.locator('#habitBoard .todo-row[data-id=night]').count(),1);await switchTo('calendar');await p.locator('#habitCalendarOptions [data-sv-span=day]').click();assert.equal(await p.locator('#habitTimeDays [data-event-id^="night|"]').count(),0);await p.locator('#classificationSideHost [data-group-eye=g1]').click();
 assert.equal(await p.locator('#habitTimeDays [data-event-id="night|planned|2026-10-03"]').count(),1);assert.equal(await p.locator('#habitTimeDays [data-event-id^="midnight|"]').count(),0);assert.equal(await p.locator('#habitTimeDays [data-sv-resize]').count(),0);
 await p.locator('#habitCalendarOptions [data-sv-span=day]').click();await p.locator('#habitDayCount').selectOption('4');assert.equal(await p.locator('#habitTimeDays .sv-day').count(),4);assert((await p.locator('#habitTimeDays .sv-timed-cards .sv-event').first().boundingBox()).width>=110);assert(await p.locator('#habitTimeDays [data-event-id="long|planned|2026-10-03"] .sv-event-open').first().evaluate(e=>{const r=document.createRange();r.selectNodeContents(e.firstChild);return r.getBoundingClientRect().top-e.getBoundingClientRect().top<25;}));await p.screenshot({path:'test-results/habit-views/calendar.png'});
 const model=await p.evaluate(()=>habitViews.occurrenceRows({start:'2026-10-01',end:'2026-10-20'}));
 assert(model.filter(r=>r.habit_id==='night'&&r.status==='open').every(r=>r.occurrence_date<='2026-10-10'));assert(model.filter(r=>r.habit_id==='paused'&&r.status==='open').every(r=>r.occurrence_date>='2026-10-06'));assert(model.filter(r=>r.habit_id==='arch'&&r.status==='open').every(r=>r.occurrence_date<'2026-10-04'));
 const snapshot=model.find(r=>r.record_id==='log1');assert.equal(snapshot.start_minute,1380);assert.equal(snapshot.duration_minutes,120);assert.equal(snapshot.occurrence_date,null);assert.equal(snapshot.record_date,'2026-10-02');assert.equal(model.find(r=>r.record_id==='old').duration_minutes,null);
 assert.deepEqual(model.filter(r=>r.habit_id==='weekly'&&r.status==='open').map(r=>r.occurrence_date),['2026-10-03','2026-10-05','2026-10-07']);assert.equal(await p.locator('[data-overdue-habit=late]').count(),1);
 await p.locator('#habitCalendarOptions [data-sv-format=blocks]').click();await p.locator('#habitTimeDays [data-block-id=block]').first().click();assert.equal(await p.locator('#ha_time').inputValue(),'09:00');assert.equal(await p.locator('#ha_endtime').inputValue(),'12:00');await p.evaluate(()=>closeHabitAddSheet());await p.locator('#habitCalendarOptions [data-sv-format=timeline]').click();
 await p.locator('#classificationSideHost [data-group-select=g1]').click();await p.locator('#habitAddBtn').click();assert.equal(await p.locator('#ha_group_id').inputValue(),'g1');assert.equal(await p.locator('#ha_start').inputValue(),'2026-10-04');await p.evaluate(()=>closeHabitAddSheet());await p.locator('#classificationSideHost [data-group-select=all]').click();
 await p.locator('#habitCalendarOptions [data-sv-span=month]').click();assert.equal(await p.locator('#habitCalGrid [data-date="2026-10-04"] [data-event-id^="midnight|"]').count(),0);await p.screenshot({path:'test-results/habit-views/month.png'});assert.equal(await writes(),0);
 // One overnight occurrence has one date key across both visible fragments.
 let cb=p.locator('#habitCalGrid [data-date="2026-10-04"] [data-occurrence="night|planned|2026-10-03"][data-habit-action=done]');await cb.click();await p.waitForFunction(()=>mockRows.tok_habit_logs.some(r=>r.habit_id==='night'&&r.done_date==='2026-10-03'));
 assert.equal(await p.evaluate(()=>mockRows.tok_habit_logs.filter(r=>r.habit_id==='night').length),1);await p.locator('#habitCalGrid [data-date="2026-10-04"] [data-occurrence="night|done|2026-10-03"][data-habit-action=undone]').click();await p.waitForFunction(()=>!mockRows.tok_habit_logs.some(r=>r.habit_id==='night'));
 await p.locator('#habitCalGrid [data-date="2026-10-03"] [data-occurrence="night|planned|2026-10-03"][data-habit-action=skip]').click();await p.waitForFunction(()=>mockRows.tok_habit_skips.some(r=>r.habit_id==='night'));await p.locator('#habitCalGrid [data-occurrence="night|skipped|2026-10-03"][data-habit-action=unskip]').click();await p.waitForFunction(()=>!mockRows.tok_habit_skips.some(r=>r.habit_id==='night'));
 const sourceBefore=await p.evaluate(()=>JSON.stringify(mockRows.tok_habits));await p.locator('[data-hv-late=late]').click();await p.waitForFunction(()=>mockRows.tok_habit_logs.some(r=>r.habit_id==='late'));assert.equal(await p.evaluate(()=>mockRows.tok_habit_logs.find(r=>r.habit_id==='late').done_date),'2026-10-04');assert.equal(await p.evaluate(()=>JSON.stringify(mockRows.tok_habits)),sourceBefore);
 await p.locator('#habitStatus').selectOption('done');assert.equal(await p.locator('#habitCalGrid [data-event-id^="record|planned|"]').count(),0);assert(await p.locator('#habitCalGrid [data-event-id="record|done|2026-10-02"]').count());await p.locator('#habitStatus').selectOption('all');
 // Failure restores status, and repeated actions have a single write key.
 await p.evaluate(()=>mockFailure='isolated failure');cb=p.locator('#habitCalGrid [data-occurrence="night|planned|2026-10-03"][data-habit-action=done]').first();await cb.click();assert.equal(await p.evaluate(()=>mockRows.tok_habit_logs.filter(r=>r.habit_id==='night').length),0);assert.match(await p.locator('#habitSaveStatus').textContent(),/저장하지 못/);
 // Same key across fragments cannot issue two concurrent inserts.
 await p.evaluate(()=>{mockDelay=150;const bs=[...document.querySelectorAll('[data-occurrence="night|planned|2026-10-03"][data-habit-action=done]')];bs[0].click();bs[1].click();});
 await p.waitForFunction(()=>mockRows.tok_habit_logs.filter(r=>r.habit_id==='night').length===1);await p.waitForFunction(()=>document.querySelector('#habitSaveStatus').textContent==='상태를 저장했어요.');
 await p.locator('#habitCalGrid [data-occurrence="night|done|2026-10-03"][data-habit-action=undone]').first().click();await p.waitForFunction(()=>!mockRows.tok_habit_logs.some(r=>r.habit_id==='night'));
 // Account changes do not hydrate the new account with an old asynchronous result.
 await p.evaluate(async()=>{mockDelay=150;const pending=setHabitDayStatus('night','2026-10-03','done');appSymbolUserId='other';tasks=[];habitLogs=[];habitSkips=[];habitViews.bind();await pending;window.ownerLeak=habitLogs.length;appSymbolUserId='test';await loadAll();});assert.equal(await p.evaluate(()=>ownerLeak),0);
 await p.evaluate(()=>setHabitDayStatus('night','2026-10-03','undone'));
 // Actual pointer ranges open unsaved forms; habit item gestures never update source periods.
 await p.locator('#habitCalendarOptions [data-sv-span=day]').click();await p.evaluate(()=>habitViews.selectDate('2026-10-04'));
 const point=async n=>{const axis=p.locator('#habitTimeDays [data-time-date="2026-10-04"]');await axis.locator('[data-minute="'+Math.floor(n/30)*30+'"]').scrollIntoViewIfNeeded();const b=await axis.boundingBox();return {x:b.x+b.width*.9,y:b.y+(n-Number(await axis.getAttribute('data-min-minute')))*Number(await axis.getAttribute('data-time-scale'))};};
 const drag=async(a,b,cancel=false)=>{await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:8});if(cancel)await p.keyboard.press('Escape');await p.mouse.up();};
 // Inclusive all-day range, Escape, and invalid off-calendar drop.
 await p.locator('#habitCalendarOptions [data-sv-span=day]').click();await p.locator('#habitDayCount').selectOption('4');
 const allA=p.locator('#habitTimeDays [data-all-date="2026-10-04"]'),allB=p.locator('#habitTimeDays [data-all-date="2026-10-05"]');await allA.scrollIntoViewIfNeeded();let ba=await allA.boundingBox(),bb=await allB.boundingBox();
 let rangeBefore=await writes();await drag({x:ba.x+ba.width-10,y:ba.y+10},{x:bb.x+bb.width-10,y:bb.y+10});assert(await p.locator('#habitAddSheetBg').isVisible());assert.equal(await p.locator('#ha_start').inputValue(),'2026-10-04');assert.equal(await p.locator('#ha_end').inputValue(),'2026-10-05');assert(await p.locator('#ha_allday').isChecked());assert.equal(await p.locator('#ha_repeat_end').inputValue(),'');await p.evaluate(()=>closeHabitAddSheet());assert.equal(await writes(),rangeBefore);
 await p.locator('#habitCalendarOptions [data-sv-span=day]').click();await p.locator('#habitDayCount').selectOption('1');
 let a=await point(660),b=await point(690);a=await point(660);let before=await writes();await drag(a,b);assert(await p.locator('#habitAddSheetBg').isVisible());assert.equal(await p.locator('#ha_time').inputValue(),'11:00');assert.equal(await p.locator('#ha_endtime').inputValue(),'11:30');assert.equal(await p.locator('#ha_repeat_end').inputValue(),'');assert.equal(await writes(),before);await p.evaluate(()=>closeHabitAddSheet());
 a=await point(660);b=await point(690);a=await point(660);await drag(a,b,true);assert(!(await p.locator('#habitAddSheetBg').isVisible()));assert.equal(await writes(),before);
 const item=p.locator('#habitTimeDays [data-event-id="night|planned|2026-10-03"] .sv-event-open');await item.scrollIntoViewIfNeeded();const box=await item.boundingBox();await drag({x:box.x+box.width/2,y:box.y+Math.min(12,box.height/2)},{x:box.x+box.width/2,y:box.y+Math.min(12,box.height/2)+30});assert(await p.locator('#habitSheetBg').isVisible());assert.equal(await writes(),before);await p.evaluate(()=>closeHabitSheet());
 await switchTo('list');await p.locator('#habitsTabRow [data-tab=archived]').click();assert.equal(await p.locator('#todoList .todo-row[data-id=arch]').count(),1);await p.screenshot({path:'test-results/habit-views/archived.png'});await p.locator('#todoList .togglebtn[data-id=arch]').click();await p.waitForFunction(()=>mockRows.tok_habits.find(h=>h.id==='arch').is_active);await p.locator('#habitsTabRow [data-tab=ended]').click();assert.equal(await p.locator('#todoList .todo-row[data-id=end]').count(),1);await p.locator('#todoList .togglebtn[data-id=end]').click();await p.waitForFunction(()=>mockRows.tok_habits.find(h=>h.id==='end').end_date===null);await p.locator('#habitsTabRow [data-tab=active]').click();
 await p.locator('#todoList [data-id=night] .info').click();assert(await p.locator('#habitSheetBg').isVisible());assert.equal(await p.locator('#hs_name').inputValue(),'밤을 넘는 습관');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.getAttribute('role')),'button');
 await p.evaluate(()=>scrollTo(0,180));const listScroll=await p.evaluate(()=>scrollY);await p.locator('#pageSidebarItems [data-sidebar-tab=board]').click();await p.locator('#pageSidebarItems [data-sidebar-tab=list]').click();assert.equal(await p.evaluate(()=>scrollY),listScroll);
 await switchTo('calendar');await p.locator('#habitCalendarOptions [data-sv-span=day]').click();await p.locator('#habitDayCount').selectOption('4');const settings=await p.evaluate(()=>({...habitViews.state(),date:document.querySelector('#habitAnchor').value}));await p.locator('#sidebarAllMenuBtn').click();assert.deepEqual(await p.evaluate(()=>({...habitViews.state(),date:document.querySelector('#habitAnchor').value})),settings);
 for(const theme of ['default','black','cheese'])for(const [width,height] of [[1440,900],[1366,768],[390,844],[760,844],[761,844]]){
  await p.evaluate(theme=>{document.documentElement.dataset.theme=theme;},theme);await p.setViewportSize({width,height});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/habit-views/${theme}-${width}.png`});
 }
 await p.evaluate(()=>{showPage('habits');habitViews.option('mode','list');});await p.setViewportSize({width:1366,height:768});await p.locator('#pageSidebarItems [data-sidebar-tab=board]').focus();await p.keyboard.press('Enter');assert(await p.locator('#habitBoard').isVisible());
 await p.evaluate(async()=>{for(let i=0;i<40;i++)mockRows.tok_habits.push({...tasks[0],id:'many'+i,name:'매우 긴 이름의 습관 '+i+' — 여러 항목과 긴 제목을 보드와 모바일에서 읽을 수 있는지 검증하는 자료입니다',group_id:null,category_id:null,project_id:null,repeat_unit:null,all_day:true,start_minute:null,duration_minutes:null,end_time:null,occurrence_start_date:'2026-10-04',occurrence_end_date:'2026-10-04'});await loadAll();habitViews.option('mode','list');});
 assert.equal(await p.locator('#todoList .todo-row').count(),await p.evaluate(()=>tasks.filter(h=>habitLifecycleState(h,todayStr())==='active').length));await switchTo('board');assert.equal(await p.locator('#habitBoard .todo-row').count(),await p.evaluate(()=>tasks.filter(h=>habitLifecycleState(h,todayStr())==='active').length));
 await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'test-results/habit-views/mobile-board.png'});await switchTo('calendar');await p.locator('#habitTimeView').scrollIntoViewIfNeeded();await p.screenshot({path:'test-results/habit-views/mobile-calendar.png'});
 assert.deepEqual(await p.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);}),[]);assert.deepEqual(errors,[]);
 console.log('PASS habit source list/board, bounded/pause-aware occurrences, literal snapshots, midnight, continuation identity, completion/skip/late/failure, native range forms, drag prohibition, archive/resume, filters/state, themes/viewports/keyboard, no errors/duplicate IDs');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
