const assert=require('node:assert/strict'),fs=require('node:fs');const {chromium}=require('playwright');const {fixture}=require('./period-fixture.cjs');
(async()=>{
 const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await b.newPage({viewport:{width:1440,height:900},timezoneId:'Asia/Seoul'});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Failed to load resource: net::ERR_FAILED'))errors.push(m.text());});p.on('dialog',d=>d.accept());
 try{
  await fixture(p);await p.evaluate(async()=>{
   const timed={allDay:false,startDate:'2026-10-03',endDate:'2026-10-05',startTime:'23:00',endTime:'01:00'},all={allDay:true,startDate:'2026-10-03',endDate:'2026-10-05'};
   mockRows.tok_events=[{id:'e-time',title:'기간 일정',...OnekanPeriod.patch('event',timed)},{id:'e-all',title:'종일 기간',...OnekanPeriod.patch('event',all)},{id:'e-unknown',title:'시작만 일정',event_date:'2026-10-03',event_time:'09:00',duration_minutes:null},{id:'e-midnight',title:'정각 끝',...OnekanPeriod.patch('event',{...timed,endDate:'2026-10-04',endTime:'00:00'})}];
   mockRows.tok_todos=[{id:'t-time',title:'기간 할일',is_done:false,project_id:'p1',...OnekanPeriod.patch('todo',timed)},{id:'t-all',title:'종일 할일',is_done:true,completed_date:'2026-10-03',...OnekanPeriod.patch('todo',all)}];
   mockRows.tok_habits=[{id:'h-old',name:'기록 보존',is_active:true,start_date:'2026-10-03',end_date:'2026-10-31',repeat_unit:'day',repeat_interval:1,...OnekanPeriod.patch('habit',timed)},{id:'h-paused',name:'보관',is_active:false,start_date:'2026-10-03',repeat_unit:'day',...OnekanPeriod.patch('habit',all)}];
   mockRows.tok_habit_logs=[{habit_id:'h-old',done_date:'2026-09-30',start_minute:540,duration_minutes:45}];mockRows.tok_habit_skips=[{habit_id:'h-old',skip_date:'2026-09-29'}];mockRows.tok_habit_pauses=[{habit_id:'h-paused',paused_at:'2026-10-03',resumed_at:null}];mockRows.tok_projects=[{id:'p1',name:'프로젝트',sort_order:0}];
   await loadAll();homeAgendaDate='2026-10-04';await renderAgendaTimed();
  });
  const get=(kind,id)=>p.evaluate(({kind,id})=>({...agendaItemById(kind,id)}),{kind,id});
  const history=()=>p.evaluate(()=>JSON.stringify({logs:mockRows.tok_habit_logs,skips:mockRows.tok_habit_skips,pauses:mockRows.tok_habit_pauses}));const historyBefore=await history();
  const timed=await p.evaluate(()=>timedItemsForDate('2026-10-04'));assert.equal(timed.find(t=>t.id==='e-time').duration_minutes,1440);assert.equal(timed.find(t=>t.id==='t-time').duration_minutes,1440);assert(!timed.some(t=>t.id==='e-midnight'));assert(!timed.some(t=>t.id==='h-paused'));
  for(const date of ['2026-10-03','2026-10-04','2026-10-05'])assert((await p.evaluate(date=>todayAllDayItems(date),date)).some(t=>t.id==='e-all'));
  await p.evaluate(()=>{homeUpcomingStart='2026-10-04';return renderHomeUpcomingList();});assert(await p.locator('.upcoming-day[data-date="2026-10-04"] [data-id="t-time"]').count());assert(await p.locator('.upcoming-day[data-date="2026-10-04"] [data-menu-id="h-old"][data-menu-date="2026-10-03"]').count());
  await p.evaluate(()=>{calCursor='2026-10-01';showScheduleMode('calendar');calSelected='2026-10-04';renderScheduleCalendar();});assert.equal(await p.locator('#calDayList .cal-day-item[data-id="e-midnight"]').count(),0);assert.equal(await p.locator('#calDayList .cal-day-item[data-id="e-time"]').count(),1);
  await p.evaluate(()=>openEventDetail('e-time'));assert((await p.locator('#evd_when').textContent()).includes('2026-10-05 01:00'));await p.evaluate(()=>closeEventDetail(false));
  // Legacy missing endpoints survive copying and date movement (30 minute display cannot become stored duration).
  await p.evaluate(async()=>{await duplicateAgendaItem('event','e-unknown');await moveItemToZone('event','e-unknown',{zone:'planday',date:'2026-10-09'});});const unknown=await get('event','e-unknown');assert.equal(unknown.duration_minutes,null);assert.equal(unknown.end_time,undefined);const unknownCopy=await p.evaluate(()=>mockRows.tok_events.find(e=>e.title==='시작만 일정 (사본)'));assert.equal(unknownCopy.duration_minutes,null);assert.equal(unknownCopy.end_time,undefined);
  // All-day copies don't acquire times; moves preserve inclusive end date and completion state.
  await p.evaluate(async()=>{await duplicateAgendaItem('todo','t-all');await duplicateAgendaItem('event','e-all');await moveItemToZone('todo','t-all',{zone:'planday',date:'2026-10-10'});await moveItemToZone('event','e-all',{zone:'today-allday',date:'2026-10-10'});});const ta=await get('todo','t-all'),ea=await get('event','e-all');assert.equal(ta.occurrence_end_date,'2026-10-12');assert.equal(ta.is_done,true);assert.equal(ta.completed_date,'2026-10-03');assert.equal(ea.end_date,'2026-10-12');for(const row of [ta,ea]){assert.equal(row.duration_minutes,null);assert.equal(row.end_time,null);}
  // Today action and its undo translate both ends, retain time and project, and do not mark complete.
  await p.evaluate(()=>moveItemToZone('todo','t-time',{zone:'planday',date:addDaysStr(todayStr(),1)}));
  const original=await get('todo','t-time');await p.evaluate(async()=>{window.savedMove=await saveTodoToToday('t-time');await loadAll();});const move=await p.evaluate(()=>savedMove);assert.equal(move.after.todo_time,original.todo_time);assert.equal(move.after.duration_minutes,1560);assert.equal(OneDays(original.start_date,original.occurrence_end_date),OneDays(move.after.start_date,move.after.occurrence_end_date));
  await p.evaluate(()=>undoTodoToToday('t-time',savedMove));const undone=await get('todo','t-time');assert.equal(undone.occurrence_end_date,original.occurrence_end_date);assert.equal(undone.project_id,'p1');assert.equal(undone.is_done,false);
  // Existing date/repeat sheet distinguishes occurrence end from repeat end and validates timed periods.
  await p.evaluate(()=>openItemDateSheet('habit','h-old'));assert.equal(await p.locator('#idt_occ_end').inputValue(),'2026-10-05');assert.equal(await p.locator('#idt_end').inputValue(),'2026-10-31');await p.locator('#idt_occ_end').fill('2026-10-06');await p.locator('#idt_save').click();await p.waitForFunction(()=>!document.getElementById('itemDateSheetBg').classList.contains('open'));assert.equal((await get('habit','h-old')).end_date,'2026-10-31');assert.equal((await get('habit','h-old')).duration_minutes,3000);
  await p.evaluate(()=>openItemDateSheet('todo','t-time'));await p.locator('#idt_date').fill('2026-10-09');assert.equal(await p.locator('#idt_occ_end').inputValue(),'2026-10-11');await p.locator('#idt_save').click();await p.waitForFunction(()=>!document.getElementById('itemDateSheetBg').classList.contains('open'));const dateChanged=await get('todo','t-time');assert.equal(dateChanged.duration_minutes,1560);assert.equal(dateChanged.todo_time,'23:00:00');assert.equal(dateChanged.occurrence_end_date,'2026-10-11');
  // Changing the live period must not re-time an old completion or alter skips/pauses.
  const past=(await p.evaluate(()=>timedItemsForDate('2026-09-30'))).find(t=>t.id==='h-old');assert.equal(past.start_minute,540);assert.equal(past.duration_minutes,45);assert.equal(await history(),historyBefore);
  await p.evaluate(async()=>{mockRows.tok_habit_logs.push({habit_id:'h-old',done_date:'2026-10-03',start_minute:1380,duration_minutes:120});Object.assign(mockRows.tok_habits[0],OnekanPeriod.patch('habit',{allDay:true,startDate:'2026-10-03',endDate:'2026-10-03'}));await loadAll();});
  const oldContinuation=(await p.evaluate(()=>timedItemsForDate('2026-10-04'))).find(t=>t.id==='h-old'&&t.occurrence_date==='2026-10-03');assert(oldContinuation);assert.equal(oldContinuation.start_minute,0);assert.equal(oldContinuation.duration_minutes,60);assert.equal(oldContinuation.done,true);
  await p.evaluate(async()=>{Object.assign(mockRows.tok_habits[0],OnekanPeriod.patch('habit',{allDay:true,startDate:'2026-10-10',endDate:'2026-10-12'}));await loadAll();await toggleHabitForDate('h-old',true,'2026-10-10');Object.assign(mockRows.tok_habits[0],OnekanPeriod.patch('habit',{allDay:true,startDate:'2026-10-10',endDate:'2026-10-10'}));await loadAll();});
  const oldAllDayContinuation=(await p.evaluate(()=>todayAllDayItems('2026-10-12'))).find(t=>t.id==='h-old'&&t.occurrence_date==='2026-10-10');assert(oldAllDayContinuation);assert.equal(oldAllDayContinuation.done,true);
  // Actual pointer drag on a continuation moves full endpoints by 15 min (not the clipped 60 min).
  await p.evaluate(async()=>{mockRows.tok_events=[{id:'drag',title:'자정 넘어 이동',...OnekanPeriod.patch('event',{allDay:false,startDate:'2026-10-03',endDate:'2026-10-04',startTime:'23:00',endTime:'01:00'})}];mockRows.tok_todos=[];mockRows.tok_habits=[];await loadAll();showPage('home');homeAgendaDate='2026-10-04';await renderAgendaTimed();});
  const task=p.locator('#agendaTimeWrap .ag-tl-task[data-id="drag"]');await task.scrollIntoViewIfNeeded();const box=await task.boundingBox();await p.mouse.move(box.x+box.width*0.4,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width*0.4,box.y+box.height/2+9,{steps:5});await p.mouse.up();await p.waitForFunction(()=>mockRows.tok_events[0].event_time!=='23:00:00');const drag=await get('event','drag');assert.equal(drag.event_date,'2026-10-03');assert.equal(drag.event_time,'23:15:00');assert.equal(drag.end_date,'2026-10-04');assert.equal(drag.end_time,'01:15:00');assert.equal(drag.duration_minutes,120);
  // Cross-date move from the continuation shifts the original start by the same calendar delta.
  await p.evaluate(()=>moveItemToZone('event','drag',{zone:'planday',date:'2026-10-07',sourceDate:'2026-10-04'}));const moved=await get('event','drag');assert.equal(moved.event_date,'2026-10-06');assert.equal(moved.end_date,'2026-10-07');assert.equal(moved.duration_minutes,120);
  assert.deepEqual(errors,[]);console.log('calendar + details + upcoming + clipped intervals / legacy duplication / all-day date movement / completion+project+history preservation / today undo / date-repeat sheet / real continuation pointer drag PASS');
 }finally{await b.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
function OneDays(a,b){return Math.round((new Date(b+'T00:00:00')-new Date(a+'T00:00:00'))/86400000);}
