// Synthetic rows only. Browser transport is isolated; pointer gestures use actual rendered coordinates.
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
const {lanes}=require('../assets/schedule-views.js');
assert.deepEqual(lanes([{id:1,start_minute:0,duration_minutes:60},{id:2,start_minute:30,duration_minutes:60},{id:3,start_minute:90,duration_minutes:30}]).map(x=>[x.id,x.lane,x.columns]),[[1,0,2],[2,1,2],[3,0,1]]);
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:900},timezoneId:'Asia/Seoul',hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource|net::ERR_FAILED/.test(m.text()))errors.push(m.text());});await fixture(p);fs.mkdirSync('test-results/schedule-views',{recursive:true});
 await p.evaluate(async()=>{const timed=(startDate,endDate,startTime,endTime)=>OnekanPeriod.patch('event',{allDay:false,startDate,endDate,startTime,endTime});const all=(a,b)=>OnekanPeriod.patch('event',{allDay:true,startDate:a,endDate:b});
  mockRows.tok_events=[{id:'night',user_id:'test',title:'자정을 넘는 일정',category_id:'g1',shared_category_id:'c1',memo:'보존 메모',...timed('2026-10-03','2026-10-04','23:00','01:00')},{id:'midnight',user_id:'test',title:'자정 종료',...timed('2026-10-03','2026-10-04','23:00','00:00')},{id:'overlap-a',user_id:'test',title:'겹침 A',...timed('2026-10-04','2026-10-04','09:07','10:08')},{id:'overlap-b',user_id:'test',title:'겹침 B 아주 긴 제목을 표시하고 겹침 열도 확인합니다',...timed('2026-10-04','2026-10-04','09:30','10:30')},{id:'all',user_id:'test',title:'여러 날 종일',category_id:'g1',...all('2026-10-02','2026-10-06')},{id:'empty',user_id:'test',title:'종료 없음',event_date:'2026-10-04',event_time:'13:00',duration_minutes:null},{id:'repeat',user_id:'test',title:'반복 보호',repeat_unit:'day',...timed('2026-10-04','2026-10-04','14:00','15:00')},{id:'outside',user_id:'test',title:'블럭 밖',...timed('2026-10-04','2026-10-04','03:00','04:00')}];
  mockRows.tok_event_categories=[{id:'g1',name:'회사',color:'#456789'},{id:'g2',name:'빈 그룹'}];mockRows.tok_habit_categories=[{id:'c1',name:'행정'},{id:'ca',name:'보관 범주',is_archived:true}];mockRows.tok_time_blocks=[{id:'b1',title:'오전',start_minute:540,end_minute:600},{id:'b2',title:'이어지는 블럭',start_minute:600,end_minute:720}];await loadAll();calSelected='2026-10-04';calCursor='2026-10-01';showPage('schedule');showScheduleMode('calendar');});
 const writes=()=>p.evaluate(()=>mockWrites.length),row=id=>p.evaluate(id=>({...mockRows.tok_events.find(x=>x.id===id)}),id);
 assert.equal(await p.locator('#scheduleSidebarNav [data-schedule-mode]').count(),3);assert(await p.locator('#calGrid').isVisible());const before=await writes();
 await p.locator('#scheduleCalendarOptions [data-sv-span=day]').click();assert.equal(await p.locator('.sv-day').count(),1);assert.equal(await p.locator('[data-event-id=midnight]').count(),0);assert.equal(await p.locator('[data-event-id=night]').count(),1);assert.equal(await p.locator('[data-event-id=night]').getAttribute('data-date'),'2026-10-04');
 const overlap=await p.locator('.sv-timed-cards [data-event-id^=overlap]').evaluateAll(es=>es.map(e=>({left:e.style.left,width:e.style.width})));assert.equal(overlap.length,2);assert.notEqual(overlap[0].left,overlap[1].left);assert.equal((await row('overlap-a')).event_time,'09:07:00');
 await p.screenshot({path:'test-results/schedule-views/day.png'});await p.locator('#scheduleCalendarOptions [data-sv-span=four]').click();assert.deepEqual(await p.locator('.sv-day').evaluateAll(es=>es.map(e=>e.dataset.svDate)),['2026-10-04','2026-10-05','2026-10-06','2026-10-07']);await p.locator('#calNextBtn').click();assert.equal(await p.locator('.sv-day').first().getAttribute('data-sv-date'),'2026-10-08');await p.locator('#calPrevBtn').click();assert.equal(await p.evaluate(()=>calSelected),'2026-10-04');await p.screenshot({path:'test-results/schedule-views/four.png'});
 // Blocks include partially uncovered rows and preserve identity across block copies.
 await p.locator('#scheduleCalendarOptions [data-sv-format=blocks]').click();assert(await p.locator('.sv-block').filter({has:p.locator('[data-event-id=outside]')}).count());assert.equal(await p.locator('.sv-day').first().locator('[data-event-id=overlap-a]').count(),2);await p.locator('.sv-day').first().locator('[data-block-id=b2]').click();assert.equal(await p.locator('#cev_time').inputValue(),'10:00');assert.equal(await p.locator('#cev_endtime').inputValue(),'12:00');await p.evaluate(()=>hideCalEventSheet());await p.screenshot({path:'test-results/schedule-views/blocks.png'});
 await p.locator('#scheduleSidebarNav [data-schedule-mode=list]').click();await p.locator('#scheduleRangeStart').fill('2026-10-04');await p.locator('#scheduleRangeEnd').fill('2026-10-05');await p.locator('#scheduleRangeApply').click();assert(await p.locator('#scheduleList .sv-card[data-id=night]').count());assert(await p.locator('#scheduleList [data-id=all]').count());await p.locator('#scheduleGroup').selectOption('none');assert.equal(await p.locator('#scheduleList .sv-card[data-id=night]').count(),1);await p.locator('#scheduleSort').selectOption('name');const names=await p.locator('#scheduleList .sv-open strong').allTextContents();assert.deepEqual(names,names.slice().sort((a,b)=>a.localeCompare(b,'ko')));
 await p.locator('#scheduleGroup').selectOption('category');assert(await p.locator('#scheduleList').textContent().then(t=>t.includes('미지정')));await p.screenshot({path:'test-results/schedule-views/list.png'});await p.locator('#scheduleSidebarNav [data-schedule-mode=board]').click();assert.equal(await p.locator('.sv-board-column[data-bucket=none]').count(),1);assert.equal(await p.locator('.sv-board-column[data-bucket=g2]').count(),1);await p.locator('#scheduleBoardBy').selectOption('category');assert(await p.locator('.sv-board-column[data-bucket=c1] [data-id=night]').count());assert.equal(await writes(),before);await p.screenshot({path:'test-results/schedule-views/board.png'});
 await p.locator('#classificationSideHost [data-group-eye=g1]').click();assert(await p.locator('#scheduleBoard [data-id=night]').count());await p.locator('#classificationSideHost [data-group-select=g1]').click();assert.equal(await p.locator('#scheduleBoard [data-id=overlap-a]').count(),0);await p.locator('#scheduleSidebarNav [data-schedule-mode=calendar]').click();assert.equal(await p.locator('#scheduleTimeDays [data-event-id=night]').count(),0);await p.locator('#classificationSideHost [data-group-eye=g1]').click();await p.locator('#classificationSideHost [data-group-select=all]').click();assert.equal(await writes(),before);
 await p.locator('#scheduleCalendarOptions [data-sv-format=timeline]').click();await p.locator('#scheduleCalendarOptions [data-sv-span=day]').click();
 const point=async(date,minute,xFraction=.85)=>{const axis=p.locator('[data-time-date="'+date+'"]');await axis.locator('.sv-hour').nth(Math.min(23,Math.floor(minute/60))).scrollIntoViewIfNeeded();const r=await axis.boundingBox();return {x:r.x+r.width*xFraction,y:r.y+minute};};
 const gesture=async(a,c,escape=false)=>{await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(c.x,c.y,{steps:8});if(escape)await p.keyboard.press('Escape');await p.mouse.up();};
 // Empty 15-minute range -> unsaved editor, reverse normalization and exact endpoints.
 let a=await point('2026-10-04',660),c=await point('2026-10-04',690);a=await point('2026-10-04',660);await gesture(c,a);await p.locator('#calEventSheetBg').waitFor({state:'visible'});assert.equal(await p.locator('#cev_time').inputValue(),'11:00');assert.equal(await p.locator('#cev_endtime').inputValue(),'11:30');assert.equal(await writes(),before);await p.evaluate(()=>hideCalEventSheet());
 // Real move preserves nonperiod fields, exact duration; click suppression avoids opening details.
 a=await point('2026-10-04',585,.3);c=await point('2026-10-04',645,.3);a=await point('2026-10-04',585,.3);await gesture(a,c);await p.waitForFunction(()=>!document.querySelector('[data-page=schedule].page').hasAttribute('aria-busy'));const moved=await row('overlap-a');assert.equal(moved.duration_minutes,61);assert.notEqual(moved.event_time,'09:07:00');assert(!(await p.locator('#evDetailBg').isVisible()));
 const savedCount=await writes();a=await point('2026-10-04',645,.3);c=await point('2026-10-04',705,.3);a=await point('2026-10-04',645,.3);await gesture(a,c,true);assert.equal(await writes(),savedCount);
 // Failure and duplicate prevention use a deferred isolated response.
 const original=await row('night');await p.evaluate(async()=>{mockFailure='test write failure';await scheduleViews.save(events.find(x=>x.id==='night'),{allDay:false,startDate:'2026-10-05',endDate:'2026-10-06',startTime:'23:00',endTime:'01:00'});});assert.deepEqual(await row('night'),original);assert((await p.locator('#scheduleSaveStatus').textContent()).includes('원래 위치'));
 await p.evaluate(async()=>{const row=events.find(e=>e.id==='night'),period={...OnekanPeriod.read('event',row),startDate:'2026-10-05',endDate:'2026-10-06'};await Promise.all([scheduleViews.save(row,period),scheduleViews.save(row,period)]);});assert.equal(await writes(),savedCount+1);const night=await row('night');assert.equal(night.memo,'보존 메모');assert.equal(night.category_id,'g1');assert.equal(night.shared_category_id,'c1');assert.equal(night.duration_minutes,120);
 // Month gestures: all-day range, date movement, invalid outside drop, resize, repeat/legacy protection.
 await p.locator('#scheduleCalendarOptions [data-sv-span=month]').click();await p.screenshot({path:'test-results/schedule-views/month.png'});
 const cell=async d=>{const el=p.locator('#calGrid [data-date="'+d+'"]');await el.scrollIntoViewIfNeeded();const r=await el.boundingBox();return {x:r.x+r.width*.75,y:r.y+r.height-8};};
 a=await cell('2026-10-10');c=await cell('2026-10-12');a=await cell('2026-10-10');await gesture(a,c);assert.equal(await p.locator('#cev_date').inputValue(),'2026-10-10');assert.equal(await p.locator('#cev_end').inputValue(),'2026-10-12');assert(await p.locator('#cev_allday').isChecked());await p.evaluate(()=>hideCalEventSheet());
 const chip=p.locator('#calGrid [data-date="2026-10-02"] .cal-chip[data-id=all]');const r=await chip.boundingBox();c=await cell('2026-10-03');await gesture({x:r.x+20,y:r.y+8},c);await p.waitForFunction(()=>mockRows.tok_events.find(e=>e.id==='all').event_date==='2026-10-03');assert.equal((await row('all')).end_date,'2026-10-07');
 let count=await writes();const ch=p.locator('#calGrid .cal-chip[data-id=night]').first();const cr=await ch.boundingBox();await gesture({x:cr.x+20,y:cr.y+8},{x:1,y:1});assert.equal(await writes(),count);
 const h=p.locator('#calGrid [data-date="2026-10-07"] .cal-chip[data-id=all] [data-sv-resize]');const hr=await h.boundingBox();c=await cell('2026-10-09');await gesture({x:hr.x+3,y:hr.y+5},c);await p.waitForFunction(()=>mockRows.tok_events.find(e=>e.id==='all').end_date==='2026-10-09');
 await p.locator('#scheduleCalendarOptions [data-sv-span=day]').click();
 for(const [id,minute] of [['repeat',840],['empty',780]]){const el=p.locator('#scheduleTimeDays [data-event-id='+id+']');await el.scrollIntoViewIfNeeded();const box=await el.boundingBox();const axis=await p.locator('[data-time-date="2026-10-04"]').boundingBox();c={x:box.x+20,y:axis.y+minute+75};count=await writes();await gesture({x:box.x+20,y:box.y+10},c);assert(await p.locator('#calEventSheetBg').isVisible());assert.equal(await writes(),count);await p.evaluate(()=>hideCalEventSheet());}
 // Timeline resize uses explicit dates and rejects a reversed endpoint.
 const resize=p.locator('#scheduleTimeDays [data-event-id=overlap-b] [data-sv-resize]');await resize.scrollIntoViewIfNeeded();const rb=await resize.boundingBox(),axis=await p.locator('[data-time-date="2026-10-04"]').boundingBox();await gesture({x:rb.x+4,y:rb.y+3},{x:rb.x+4,y:axis.y+660});await p.waitForFunction(()=>mockRows.tok_events.find(e=>e.id==='overlap-b').end_time==='11:00:00');assert.equal((await row('overlap-b')).duration_minutes,90);
 const resized=await row('overlap-b');await p.evaluate(()=>scheduleViews.save(events.find(e=>e.id==='overlap-b'),{allDay:false,startDate:'2026-10-04',startTime:'09:30',endDate:'2026-10-04',endTime:'08:00'}));assert.deepEqual(await row('overlap-b'),resized);
 await p.locator('#scheduleCalendarOptions [data-sv-span=month]').click();const blank=p.locator('#calGrid .cal-cell[data-date="2026-10-14"]');await blank.dblclick({position:{x:60,y:65}});assert(await p.locator('#calEventSheetBg').isVisible());assert.equal(await p.locator('#cev_date').inputValue(),'2026-10-14');await p.evaluate(()=>hideCalEventSheet());await p.evaluate(()=>{calSelected='2026-10-04';renderScheduleCalendar();});
 // Four-day timed selection across midnight uses explicit dates and never writes until Save.
 await p.locator('#scheduleCalendarOptions [data-sv-span=four]').click();a=await point('2026-10-04',1350);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.locator('#scheduleTimeScroll').evaluate(el=>el.scrollTop=0);c=await point('2026-10-05',15);await p.mouse.move(c.x,c.y,{steps:6});await p.mouse.up();assert.equal(await p.locator('#cev_date').inputValue(),'2026-10-04');assert.equal(await p.locator('#cev_time').inputValue(),'22:30');assert.equal(await p.locator('#cev_end').inputValue(),'2026-10-05');assert.equal(await p.locator('#cev_endtime').inputValue(),'00:15');await p.evaluate(()=>hideCalEventSheet());
 // No block configuration still exposes timed rows, including legacy missing ends.
 await p.locator('#scheduleCalendarOptions [data-sv-format=blocks]').click();await p.evaluate(()=>{timeBlocks=[];renderScheduleCalendar();});assert(await p.locator('#scheduleTimeDays [data-event-id=outside]').count());await p.locator('#scheduleCalendarOptions [data-sv-format=timeline]').click();
 // Per-account preferences, view/filter/scroll preservation and responsive theme evidence.
 await p.locator('#scheduleCalendarOptions [data-sv-span=four]').click();await p.locator('#scheduleTimeScroll').evaluate(e=>{e.scrollTop=500;e.scrollLeft=50;});await p.locator('#sidebarAllMenuBtn').click();assert.equal(await p.locator('#scheduleTimeScroll').evaluate(e=>e.scrollTop),500);await p.locator('#mainSidebarNav [data-page=schedule]').click();
 const prefs=await p.evaluate(()=>localStorage.getItem('tok_schedule_views:test'));assert(prefs.includes('four'));await p.evaluate(()=>{appSymbolUserId='other';scheduleViews.bind();});assert.equal(await p.evaluate(()=>scheduleViews.state().span),'month');await p.evaluate(()=>{appSymbolUserId='test';scheduleViews.bind();});assert.equal(await p.evaluate(()=>scheduleViews.state().span),'four');
 await p.evaluate(()=>document.getElementById('scheduleSaveStatus').textContent='');
 for(const [width,height,theme] of [[1440,900,'basic'],[1366,768,'black'],[390,844,'cheese'],[760,768,'basic'],[761,768,'basic']]){await p.setViewportSize({width,height});await p.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),JSON.stringify(await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll(".page[data-page=schedule] *")].filter(e=>e.getBoundingClientRect().right>innerWidth+1&&e.getClientRects().length&&!e.closest(".sv-time-scroll,.sv-board")).map(e=>({tag:e.tagName,id:e.id,cls:e.className,right:e.getBoundingClientRect().right})).slice(0,8)}))));await p.screenshot({path:'test-results/schedule-views/'+width+'-'+theme+'.png'});}
 await p.locator('#scheduleAnchor').fill('2026-10-04');await p.locator('#scheduleAnchor').press('Tab');await p.setViewportSize({width:390,height:844});await p.locator('#scheduleModeBoardBtn').click();assert(await p.locator('#scheduleBoard').isVisible());await p.locator('#scheduleModeCalendarBtn').click();count=await writes();await p.touchscreen?.tap?.(1,1);assert.equal(await writes(),count);
 assert.deepEqual(await p.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);}),[]);assert.deepEqual(errors,[]);console.log('PASS schedule day/four/month, lanes + actual clips, blocks/outside, list/board, independent filters, real pointer range/move/resize/cancel/failure/repeat/legacy guards, ownership/preferences, mobile/theme/keyboard/no navigation writes or errors');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
