const assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await fixture(p);
 await p.evaluate(async()=>{mockRows.tok_events=Array.from({length:25},(_,i)=>({id:'e'+i,user_id:'test',title:'일정 '+i,event_date:'2026-10-'+String(i+1).padStart(2,'0'),end_date:'2026-10-'+String(i+1).padStart(2,'0'),all_day:true,category_id:'g'}));mockRows.tok_event_categories=[{id:'g',user_id:'test',name:'약속',sort_order:0}];await loadAll();showPage('schedule');calSelected='2026-10-07';calCursor='2026-10';scheduleViews.selectView('month');});
 const calendar=p.locator('#calGrid'),panel=p.locator('#scheduleMonthAgenda');assert(await panel.isVisible());assert.equal(await panel.locator('[data-agenda-event]').count(),25);assert.equal(await p.locator('#scheduleModeToggle [data-schedule-view]:visible').count(),0);
 const before=(await calendar.boundingBox()).width;await p.locator('#scheduleAgendaClose').click();assert.equal(await panel.isVisible(),false);assert((await calendar.boundingBox()).width>before);
 await p.locator('[data-month-date="2026-10-24"]').click();assert(await panel.isVisible());assert.equal(await p.locator('#scheduleAgendaScroll').evaluate(el=>el.scrollTop>0),true);assert.equal(await p.evaluate(()=>document.activeElement.closest('[data-agenda-date]').dataset.agendaDate),'2026-10-24');
 await p.locator('[data-month-date="2026-10-28"]').click();assert.equal(await panel.locator('[data-agenda-date="2026-10-28"] .cal-day-empty').textContent(),'일정 없음');
 await p.locator('#calGrid .cal-cell[data-date="2026-10-28"]').click({position:{x:65,y:65}});assert(await p.locator('#cev_title').isVisible());assert.equal(await p.locator('#cev_date').inputValue(),'2026-10-28');await p.locator('#cev_cancel').click();assert.equal(await p.evaluate(()=>mockWrites.length),0);
 await p.locator('#calGrid .cal-chip[data-id="e5"] .cal-chip-title').click();assert.equal(await p.locator('#cev_title').isVisible(),false);await p.keyboard.press('Escape');
 // Real pointer range selection opens one editor with the dragged date period.
 const start=await p.locator('#calGrid .cal-cell[data-date="2026-10-27"]').boundingBox(),end=await p.locator('#calGrid .cal-cell[data-date="2026-10-29"]').boundingBox();await p.mouse.move(start.x+60,start.y+65);await p.mouse.down();await p.mouse.move(end.x+60,end.y+65,{steps:12});await p.mouse.up();assert(await p.locator('#cev_title').isVisible());assert.equal(await p.locator('#cev_date').inputValue(),'2026-10-27');assert.equal(await p.locator('#cev_end').inputValue(),'2026-10-29');await p.locator('#cev_cancel').click();
 // Real item move persists the whole period and does not open an add editor.
 const chip=await p.locator('#calGrid .cal-chip[data-id="e5"] .cal-chip-title').boundingBox(),dest=await p.locator('#calGrid .cal-cell[data-date="2026-10-13"]').boundingBox();await p.mouse.move(chip.x+10,chip.y+8);await p.mouse.down();await p.mouse.move(dest.x+60,dest.y+65,{steps:12});await p.mouse.up();await p.waitForFunction(()=>mockRows.tok_events.find(e=>e.id==='e5').event_date==='2026-10-13');assert.equal(await p.locator('#cev_title').isVisible(),false);
 await p.locator('#scheduleSidebarNav [data-schedule-view=week]').click();assert(await panel.isVisible());await p.locator('#scheduleSidebarNav [data-schedule-view=day]').click();assert(await panel.isVisible());await p.locator('#scheduleSidebarNav [data-schedule-view=list]').click();assert.equal(await panel.isVisible(),false);
 await p.locator('#scheduleSidebarNav [data-schedule-view=month]').click();await p.locator('#classificationSideHost [data-group-eye=g]').click();assert.equal(await panel.locator('[data-agenda-event]').count(),0);await p.locator('#classificationSideHost [data-group-eye=g]').click();
 const icons=await p.locator('#todoIconRail [data-page=schedule]').boundingBox();await p.locator('#sidebarRailToggle').click();assert.equal(await p.locator('#classificationSideHost').isVisible(),false);const after=await p.locator('#todoIconRail [data-page=schedule]').boundingBox();assert.equal(icons.x,after.x);assert.equal(icons.y,after.y);await p.locator('#sidebarRailToggle').click();await p.locator('#todoIconRail [data-page=schedule]').click();assert(await p.locator('#classificationSideHost').isVisible());
 await p.screenshot({path:'test-results/schedule-panels-desktop.png',fullPage:true});
 for(const width of [900,761]){await p.setViewportSize({width,height:900});assert(await panel.isVisible());assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 await p.setViewportSize({width:390,height:844});await p.waitForFunction(()=>!document.querySelector('[data-month-date]'));assert.equal(await panel.isVisible(),false);assert.equal(await p.locator('[data-month-date]').count(),0);assert(await p.locator('#calDayList').isVisible());assert.equal(await p.locator('#todoIconRail').isVisible(),false);assert.deepEqual(errors,[]);
 console.log('PC month agenda, independent collapse, date/blank/detail clicks, range add, item move, views/filter, fixed icons and mobile isolation PASS');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

