// Synthetic native todo rows; all network/database writes remain inside the fixture.
const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await browser.newPage({viewport:{width:1440,height:900},timezoneId:'Asia/Seoul',hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource|net::ERR_FAILED/.test(m.text()))errors.push(m.text());});await fixture(p);fs.mkdirSync('test-results/todo-views',{recursive:true});
 await p.evaluate(async()=>{
  const timed=(a,b,c,d)=>OnekanPeriod.patch('todo',{allDay:false,startDate:a,endDate:b,startTime:c,endTime:d}),all=(a,b)=>OnekanPeriod.patch('todo',{allDay:true,startDate:a,endDate:b});
  mockRows.tok_todos=[{id:'night',user_id:'test',title:'밤을 넘는 할일',group_id:'g1',tag_id:'c1',project_id:'p1',...timed('2026-10-03','2026-10-04','23:00','01:00')},{id:'midnight',user_id:'test',title:'00시 종료',...timed('2026-10-03','2026-10-04','23:00','00:00')},{id:'a',user_id:'test',title:'겹침 A',...timed('2026-10-04','2026-10-04','09:07','10:08')},{id:'b',user_id:'test',title:'겹침 B 긴 제목과 여러 연결을 표시하는 할일',...timed('2026-10-04','2026-10-04','09:30','10:30')},{id:'all',user_id:'test',title:'여러 날 종일',group_id:'g1',...all('2026-10-02','2026-10-06')},{id:'undated',user_id:'test',title:'날짜 없는 실제 할일',start_date:null,is_done:false},{id:'legacy',user_id:'test',title:'종료 없는 기존 할일',start_date:'2026-10-04',todo_time:'13:00',duration_minutes:null},{id:'repeat',user_id:'test',title:'반복 예정',group_id:'g1',tag_id:'c1',project_id:'p1',repeat_unit:'day',repeat_interval:1,end_date:'2026-10-31',...timed('2026-10-04','2026-10-05','23:00','01:00')},{id:'done',user_id:'test',title:'완료 과거 회차',repeat_unit:'day',repeat_interval:1,is_done:true,completed_date:'2026-10-03',...all('2026-10-03','2026-10-03')}];
  mockRows.tok_item_groups=[{id:'g1',kind:'todo',name:'회사',color:'#4677aa'},{id:'g2',kind:'todo',name:'빈 그룹'},{id:'ga',kind:'todo',name:'보관 그룹',is_archived:true}];mockRows.tok_habit_categories=[{id:'c1',name:'행정',color:'#8373af'}];mockRows.tok_projects=[{id:'p1',name:'목표',is_active:true}];mockRows.tok_someday=[{id:'s1',title:'언젠가 별도 항목',group_id:'g1',tag_id:'c1',project_id:'p1'}];mockRows.tok_time_blocks=[{id:'block',title:'오전',start_minute:540,end_minute:720}];await loadAll();todoViews.selectDate('2026-10-04');showPage('todos');mockWrites.length=0;
 });
 const writes=()=>p.evaluate(()=>mockWrites.length),row=id=>p.evaluate(id=>({...mockRows.tok_todos.find(r=>r.id===id)}),id),switchTo=mode=>p.locator('#pageSidebarItems [data-sidebar-tab='+mode+']:visible, #todoTopTabs [data-tab='+mode+']:visible').click();
 assert.equal(await p.evaluate(()=>todoViews.state().mode),'list');assert.equal(await p.locator('#todoCompletion').inputValue(),'open');assert.equal(await p.locator('#todoUnifiedList [data-id=s1]').count(),0);assert(await p.locator('#todoUnifiedList [data-id=undated]').count());assert.equal(await p.locator('#todoUnifiedList [data-id=done]').count(),0);await p.screenshot({path:'test-results/todo-views/list.png'});
 assert.deepEqual(await p.locator('#pageSidebarItems button').allTextContents(),['달력','목록','보드','언젠가']);assert.equal(await p.locator('#pageSidebarItems hr').count(),1);
 await p.locator('#todoGroup').selectOption('none');await p.locator('#todoSort').selectOption('name');const names=await p.locator('#todoUnifiedList .sv-open strong').allTextContents();assert.deepEqual(names,names.slice().sort((a,b)=>a.localeCompare(b,'ko')));
 for(const group of ['date','group','category','project']){await p.locator('#todoGroup').selectOption(group);assert(await p.locator('#todoUnifiedList').textContent().then(t=>t.includes(group==='date'?'날짜 없음':'미지정')));}
 await p.locator('#todoRangeStart').fill('2026-10-04');await p.locator('#todoRangeEnd').fill('2026-10-05');await p.locator('#todoRangeApply').click();await switchTo('board');assert.equal(await p.locator('#todoRangeStart').inputValue(),'2026-10-04');await switchTo('list');assert.equal(await p.locator('#todoRangeEnd').inputValue(),'2026-10-05');await p.locator('#todoRangeStart').fill('2026-10-01');await p.locator('#todoRangeEnd').fill('2026-10-31');await p.locator('#todoRangeApply').click();await switchTo('board');assert(await p.locator('#todoBoard [data-bucket=g2]').count());assert(await p.locator('#todoBoard [data-bucket=none] [data-id=undated]').count());await p.screenshot({path:'test-results/todo-views/board-groups.png'});await p.locator('#todoBoardBy').selectOption('project');assert(await p.locator('#todoBoard [data-bucket=p1] [data-id=night]').count());await p.screenshot({path:'test-results/todo-views/board.png'});
 await p.locator('#classificationSideHost [data-group-eye=g1]').click();assert(await p.locator('#todoBoard [data-id=night]').count());await switchTo('calendar');await p.locator('#todoCalendarOptions [data-sv-span=day]').click();assert.equal(await p.locator('#todoTimeDays [data-event-id=night]').count(),0);await p.locator('#classificationSideHost [data-group-eye=g1]').click();assert.equal(await p.locator('#todoTimeDays [data-event-id=night]').count(),1);assert.equal(await p.locator('#todoTimeDays [data-event-id=midnight]').count(),0);
 const geometry=await p.locator('#todoTimeDays .ag-tl-content [data-event-id]').evaluateAll(es=>es.filter(e=>['a','b'].includes(e.dataset.eventId)).map(e=>e.style.left));assert.equal(geometry.length,2);assert.notEqual(geometry[0],geometry[1]);assert.equal((await row('a')).todo_time,'09:07:00');await p.screenshot({path:'test-results/todo-views/calendar.png'});
 await p.locator('#classificationSideHost [data-group-select=g1]').click();assert.equal(await p.locator('#todoTimeDays [data-event-id=a]').count(),0);await p.locator('#todoQuickAddBtn').click();assert.equal(await p.locator('#td_group_id').inputValue(),'g1');await p.evaluate(()=>closeTodoSheet());await p.locator('#classificationSideHost [data-group-select=all]').click();
 await p.locator('#classificationSideHost [data-group-eye=default]').click();assert.equal(await p.locator('#todoTimeDays [data-event-id=a]').count(),0);await p.locator('#classificationSideHost [data-group-eye=default]').click();
 await p.locator('#todoCalendarOptions [data-sv-span=day]').click();await p.locator('#todoDayCount').selectOption('4');assert.equal(await p.locator('#todoTimeDays .sv-day').count(),4);assert.equal(await p.locator('#todoTimeDays [data-event-id=repeat]').count(),2);assert.equal(await p.locator('#todoTimeDays [data-event-id=done]').count(),0);
 await p.locator('#todoCalendarOptions [data-sv-format=blocks]').click();await p.locator('#todoTimeDays [data-block-id=block]').first().click();assert.equal(await p.locator('#td_time').inputValue(),'09:00');assert.equal(await p.locator('#td_endtime').inputValue(),'12:00');await p.evaluate(()=>closeTodoSheet());await p.locator('#todoCalendarOptions [data-sv-format=timeline]').click();
 await p.locator('#todoCalendarOptions [data-sv-span=month]').click();assert.equal(await p.locator('#todoCalGrid [data-date="2026-10-04"] [data-event-id=midnight]').count(),0);assert(await p.locator('#todoCalGrid [data-event-id=repeat]').count());assert(await p.locator('#todoCalGrid .cal-more').count());await p.screenshot({path:'test-results/todo-views/month.png'});await p.locator('#todoShowUndated').click();assert(await p.locator('#todoUnifiedList [data-id=undated]').count());assert.equal(await writes(),0);
 await p.locator('#todoUndated').uncheck();assert.equal(await p.locator('#todoUnifiedList [data-id=undated]').count(),0);await p.locator('#todoUndated').check();await p.locator('#todoCompletion').selectOption('done');assert(await p.locator('#todoUnifiedList [data-id=done]').count());assert.equal(await p.locator('#todoUnifiedList [data-id=a]').count(),0);await p.locator('#todoCompletion').selectOption('all');
 await p.locator('#todoGroup').selectOption('date');const originalDone=await row('done');await p.locator('#todoUnifiedList [data-todo-check=repeat]').first().check();await p.waitForFunction(()=>mockRows.tok_todos.some(r=>r.repeat_source_id==='repeat'));const completed=await row('repeat');assert.equal(completed.start_date,'2026-10-04');assert.equal(completed.occurrence_end_date,'2026-10-05');assert(completed.is_done);assert.deepEqual(await row('done'),originalDone);
 const next=await p.evaluate(()=>mockRows.tok_todos.find(r=>r.repeat_source_id==='repeat'));assert.equal(next.start_date,'2026-10-05');assert.equal(next.occurrence_end_date,'2026-10-06');assert.equal(next.end_date,'2026-10-31');assert.equal(next.group_id,'g1');assert.equal(next.tag_id,'c1');assert.equal(next.project_id,'p1');assert.equal(next.duration_minutes,120);
 await p.evaluate(async()=>{await setTodoDone('repeat',false);await setTodoDone('repeat',true);});assert.equal(await p.evaluate(()=>mockRows.tok_todos.filter(r=>r.repeat_source_id==='repeat').length),1);await p.locator('#todoCompletion').selectOption('open');
 // Real timeline gestures and exact duration, with failure/duplicate/legacy/repeat protection.
 await switchTo('calendar');await p.locator('#todoCalendarOptions [data-sv-span=day]').click();await p.locator('#todoDayCount').selectOption('1');
 const point=async(minute,fraction=.85)=>{const axis=p.locator('#todoTimeDays [data-time-date="2026-10-04"]');await axis.locator('..').locator('[data-minute="'+Math.floor(minute/30)*30+'"]').scrollIntoViewIfNeeded();const box=await axis.boundingBox();return {x:box.x+box.width*fraction,y:box.y+(minute-Number(await axis.getAttribute('data-min-minute')))*Number(await axis.getAttribute('data-time-scale'))};};
 const gesture=async(a,b,cancel=false)=>{await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:8});if(cancel)await p.keyboard.press('Escape');await p.mouse.up();};
 let a=await point(660),b=await point(690);a=await point(660);let before=await writes();await gesture(a,b);assert(await p.locator('#todoSheetBg').isVisible());assert.equal(await p.locator('#td_time').inputValue(),'11:00');assert.equal(await p.locator('#td_endtime').inputValue(),'11:30');assert.equal(await writes(),before);await p.evaluate(()=>closeTodoSheet());
 a=await point(585,.3);b=await point(645,.3);a=await point(585,.3);await gesture(a,b);await p.waitForFunction(()=>mockRows.tok_todos.find(r=>r.id==='a').todo_time!=='09:07:00');assert.equal((await row('a')).duration_minutes,61);assert.equal((await row('a')).is_done,undefined);
 before=await writes();a=await point(645,.3);b=await point(705,.3);a=await point(645,.3);await gesture(a,b,true);assert.equal(await writes(),before);
 const savedNight=await row('night');await p.evaluate(async()=>{mockFailure='isolated failure';await todoViews.save(todos.find(r=>r.id==='night'),{allDay:false,startDate:'2026-10-05',endDate:'2026-10-06',startTime:'23:00',endTime:'01:00'},'move');});assert.deepEqual(await row('night'),savedNight);assert.match(await p.locator('#todoSaveStatus').textContent(),/원래 위치/);
 await p.evaluate(async()=>{const row=todos.find(r=>r.id==='night'),value={...OnekanPeriod.read('todo',row),startDate:'2026-10-05',endDate:'2026-10-06'};await Promise.all([todoViews.save(row,value,'move'),todoViews.save(row,value,'move')]);});assert.equal(await writes(),before+1);assert.equal((await row('night')).group_id,'g1');assert.equal((await row('night')).tag_id,'c1');assert.equal((await row('night')).project_id,'p1');
 const legacy=await row('legacy');before=await writes();await p.evaluate(async()=>{await todoViews.save(todos.find(r=>r.id==='legacy'),{allDay:false,startDate:'2026-10-04',endDate:'2026-10-04',startTime:'13:00',endTime:'14:00'});await todoViews.save(todos.find(r=>r.id==='repeat'),{allDay:true,startDate:'2026-10-06',endDate:'2026-10-07'});});assert.equal(await writes(),before);assert.deepEqual(await row('legacy'),legacy);
 const resize=p.locator('#todoTimeDays [data-event-id=b] [data-sv-resize]');await resize.scrollIntoViewIfNeeded();const r=await resize.boundingBox(),axis=await p.locator('#todoTimeDays [data-time-date]').first().evaluate(e=>({...e.getBoundingClientRect().toJSON(),min:Number(e.dataset.minMinute),scale:Number(e.dataset.timeScale)}));await gesture({x:r.x+5,y:r.y+3},{x:r.x+5,y:axis.y+(660-axis.min)*axis.scale});await p.waitForFunction(()=>mockRows.tok_todos.find(r=>r.id==='b').end_time==='11:00:00');assert.equal((await row('b')).duration_minutes,90);await p.waitForFunction(()=>!document.querySelector('[data-page=todos].page').hasAttribute('aria-busy'));
 await p.locator('#todoTimeDays [data-event-id=legacy]').scrollIntoViewIfNeeded();await p.locator('#todoTimeScroll').evaluate(el=>el.scrollTop+=150);const lr=await p.locator('#todoTimeDays [data-event-id=legacy]').boundingBox();before=await writes();await gesture({x:lr.x+45,y:lr.y+8},{x:lr.x+45,y:lr.y+65});assert(await p.locator('#todoSheetBg').isVisible());assert.equal(await writes(),before);await p.evaluate(()=>closeTodoSheet());
 await p.locator('#todoCompletion').selectOption('all');await p.locator('#todoCalendarOptions [data-sv-span=day]').click();await p.locator('#todoDayCount').selectOption('4');const recurring=p.locator('#todoTimeDays [data-event-id=repeat]').first();await recurring.scrollIntoViewIfNeeded();const rr=await recurring.boundingBox();before=await writes();await gesture({x:rr.x+45,y:Math.max(90,rr.y+10)},{x:rr.x+45,y:Math.max(90,rr.y+10)-30});assert(await p.locator('#todoSheetBg').isVisible());assert.equal(await writes(),before);assert.equal((await row('repeat')).end_date,'2026-10-31');await p.evaluate(()=>closeTodoSheet());await p.locator('#todoCompletion').selectOption('open');
 // Month native row move and resize, reverse range proposals, invalid outside drop.
 await p.locator('#todoCalendarOptions [data-sv-span=month]').click();const cell=async date=>{const el=p.locator('#todoCalGrid .cal-cell[data-date="'+date+'"]');await el.scrollIntoViewIfNeeded();const r=await el.boundingBox();return {x:r.x+r.width*.8,y:r.y+r.height-7};};
 a=await cell('2026-10-12');b=await cell('2026-10-10');a=await cell('2026-10-12');await gesture(a,b);assert(await p.locator('#todoSheetBg').isVisible());assert(await p.locator('#td_allday').isChecked());assert.equal(await p.locator('#td_start').inputValue(),'2026-10-10');assert.equal(await p.locator('#td_end').inputValue(),'2026-10-12');await p.evaluate(()=>closeTodoSheet());
 const all=p.locator('#todoCalGrid [data-date="2026-10-02"] [data-event-id=all]');await all.scrollIntoViewIfNeeded();b=await cell('2026-10-03');const ar=await all.boundingBox();await gesture({x:ar.x+45,y:ar.y+8},b);await p.waitForFunction(()=>mockRows.tok_todos.find(r=>r.id==='all').start_date==='2026-10-03');assert.equal((await row('all')).occurrence_end_date,'2026-10-07');await p.waitForFunction(()=>!document.querySelector('[data-page=todos].page').hasAttribute('aria-busy'));
 const end=p.locator('#todoCalGrid [data-date="2026-10-07"] [data-event-id=all] [data-sv-resize]');b=await cell('2026-10-09');const er=await end.boundingBox();await gesture({x:er.x+3,y:er.y+5},b);await p.waitForFunction(()=>mockRows.tok_todos.find(r=>r.id==='all').occurrence_end_date==='2026-10-09');before=await writes();a=await cell('2026-10-10');await gesture(a,{x:1,y:1});assert.equal(await writes(),before);
 await switchTo('someday');assert(await p.locator('#somedayList [data-id=s1]').count());await p.locator('#somedayInput').fill('작성 중');await p.locator('#sidebarRailToggle').click();assert.equal(await p.locator('#somedayInput').inputValue(),'작성 중');await p.locator('#mainSidebarNav [data-page=todos]').click();assert(await p.locator('#todoSomedayView').isVisible());await p.screenshot({path:'test-results/todo-views/someday.png'});
 await switchTo('calendar');await p.locator('#todoCalendarOptions [data-sv-span=day]').click();await p.locator('#todoDayCount').selectOption('4');await p.locator('#todoTimeScroll').evaluate(el=>el.scrollTop=500);await p.locator('#sidebarRailToggle').click();assert.equal(await p.locator('#todoTimeScroll').evaluate(el=>el.scrollTop),Math.min(500,await p.locator('#todoTimeScroll').evaluate(e=>e.scrollHeight-e.clientHeight)));await p.locator('#mainSidebarNav [data-page=todos]').click();
 await p.evaluate(()=>document.getElementById('todoSaveStatus').textContent='');
 const settings=await p.evaluate(()=>localStorage.getItem('tok_todos_views:test'));assert.equal(JSON.parse(settings).days,4);await p.evaluate(()=>{appSymbolUserId='other';todoViews.bind();});assert.equal(await p.evaluate(()=>todoViews.state().mode),'list');await p.evaluate(()=>{appSymbolUserId='test';todoViews.bind();});assert.equal(await p.evaluate(()=>todoViews.state().days),4);
 for(const [width,height,theme] of [[1440,900,'white'],[1366,768,'black'],[390,844,'cheese'],[760,768,'white'],[761,768,'white']]){await p.setViewportSize({width,height});await p.evaluate(theme=>applyTheme(theme),theme);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'test-results/todo-views/'+width+'-'+theme+'.png'});}
 await p.setViewportSize({width:390,height:844});before=await writes();await p.locator('#todoTimeDays [data-event-id=b]').first().dispatchEvent('pointerdown',{pointerType:'touch',pointerId:4,button:0,clientX:160,clientY:650});await p.dispatchEvent('body','pointermove',{pointerType:'touch',pointerId:4,clientX:160,clientY:500});await p.dispatchEvent('body','pointerup',{pointerType:'touch',pointerId:4,clientX:160,clientY:500});assert.equal(await writes(),before);assert(await p.locator('#todoDragPreview').isHidden());await p.locator('#todoTopTabs [data-tab=list]').focus();await p.keyboard.press('Enter');assert(await p.locator('#todoCollection').isVisible());await p.locator('#todoQuickAddBtn').click();await p.locator('#td_title').fill('모바일 입력 보존');await p.setViewportSize({width:761,height:768});assert.equal(await p.locator('#td_title').inputValue(),'모바일 입력 보존');await p.evaluate(()=>closeTodoSheet());
 assert.deepEqual(await p.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);}),[]);assert.deepEqual(errors,[]);
 console.log('PASS todo views: native rows, undated/someday, completion/repeat history, eyes, links, pointer move/resize/range/cancel/failure, account preferences, responsive themes, no duplicate IDs/page errors');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
