const assert=require('node:assert/strict');
const {fixture}=require('./together-fixture.cjs');
(async()=>{
 const {db,as,rpc,upload,A,B,C,uuid}=await fixture();let checks=0;
 const ok=(value)=>{assert(value);checks++;};
 const reject=async(p,pattern)=>{await assert.rejects(p,pattern);checks++;};
 const room=uuid();
 await reject(rpc(null,'create_room',{id:room,name:'방',nickname:'나',rate:100}));
 await rpc(A,'create_room',{id:room,name:'그림 한 칸',nickname:'결',rate:100});
 await rpc(A,'create_room',{id:room,name:'그림 한 칸',nickname:'결',rate:100});
 const inv=(await as(A,'select * from tok_pair_invites')).rows[0];
 ok((await as(B,'select * from tok_pair_rooms')).rows.length===0);
 ok((await as(B,'select * from tok_pair_invites')).rows.length===0);
 await rpc(B,'join',{id:inv.id,nickname:'친구'});
 await reject(rpc(B,'join',{id:inv.id,nickname:'친구'}),/이미 이 방/);
 await reject(rpc(C,'join',{id:inv.id,nickname:'셋째'}),/정원/);
 ok((await as(B,'select * from tok_pair_members')).rows.length===2);
 await reject(rpc(B,'invite',{room_id:room,id:uuid()}),/방장/);
 const cancelled=uuid();await rpc(A,'invite',{room_id:room,id:cancelled});await rpc(A,'revoke_invite',{room_id:room});
 await reject(rpc(C,'join',{id:cancelled,nickname:'셋째'}),/취소/);
 const expired=uuid();await rpc(A,'invite',{room_id:room,id:expired});await db.query("update tok_pair_invites set expires_at=now()-interval '1 day' where id=$1",[expired]);
 await reject(rpc(C,'join',{id:expired,nickname:'셋째'}),/만료/);
 const plan=uuid();const p={id:plan,room_id:room,title:'직접 입력',points:5,due_date:'2026-10-02'};
 await reject(rpc(A,'plan',{...p,points:0}));await reject(rpc(A,'plan',{...p,points:1.5}));
 await reject(rpc(C,'plan',p),/참여자/);
 await rpc(A,'plan',p);await rpc(A,'plan',p);ok((await as(A,'select * from tok_pair_plans')).rows.length===1);
 const linked=uuid();await rpc(A,'plan',{...p,id:linked,source_kind:'habit',source_id:'10000000-0000-0000-0000-000000000002'});
 await reject(rpc(A,'plan',{...p,id:uuid(),source_kind:'habit',source_id:'10000000-0000-0000-0000-000000000002'}));
 await rpc(A,'plan',{...p,id:uuid(),due_date:'2026-10-03',source_kind:'habit',source_id:'10000000-0000-0000-0000-000000000002'});
 await reject(rpc(B,'plan',{...p,id:uuid(),source_kind:'todo',source_id:'10000000-0000-0000-0000-000000000001'}),/본인의/);
 const linkedRow=(await as(B,'select * from tok_pair_plans where id=$1',[linked])).rows[0];ok(linkedRow.title==='매일 그림'&&!JSON.stringify(linkedRow).includes('메모'));
 const path=`${room}/${A}/${uuid()}`,proof=uuid();await upload(A,path);
 ok((await as(B,'select * from storage.objects')).rows.length===0);
 await reject(upload(C,`${room}/${C}/${uuid()}`));
 await reject(upload(B,`${room}/${A}/${uuid()}`));
 await rpc(A,'proof',{room_id:room,id:proof,plan_id:plan,image_path:path,body:'세 장 그렸어요'});
 await rpc(A,'proof',{room_id:room,id:uuid(),plan_id:plan,image_path:path,body:'재시도'});
 ok((await as(B,'select * from storage.objects')).rows.length===1);
 await reject(rpc(A,'confirm',{room_id:room,id:proof}),/내 인증/);
 await reject(rpc(C,'confirm',{room_id:room,id:proof}),/참여자/);
 await Promise.all(Array.from({length:8},()=>rpc(B,'confirm',{room_id:room,id:proof})));
 ok((await as(A,'select * from tok_pair_ledger')).rows.length===1);
 ok((await as(A,'select sum(amount)::int as balance from tok_pair_ledger')).rows[0].balance===5);
 ok((await as(B,'select * from tok_pair_proofs')).rows[0].confirmed_by===B);
 await reject(as(A,'update tok_pair_plans set points=500 where id=$1',[plan]));
 await reject(as(A,'delete from tok_pair_proofs where id=$1',[proof]));
 ok((await as(A,"update storage.objects set name='other' where name=$1 returning *",[path])).rows.length===0);
 ok((await as(A,'delete from storage.objects where name=$1 returning *',[path])).rows.length===0);
 await reject(rpc(A,'reward',{room_id:room,id:uuid(),title:'빵',points:6,reward_date:'2026-10-02'}),/잔여/);
 const reward=uuid(),rw={room_id:room,id:reward,title:'빵',points:4,reward_date:'2026-10-02'};
 await rpc(A,'reward',rw);await rpc(A,'reward',rw);
 const results=await Promise.allSettled([rpc(A,'reward',{...rw,id:uuid(),points:1}),rpc(A,'reward',{...rw,id:uuid(),points:1})]);ok(results.filter(x=>x.status==='fulfilled').length===1);
 ok((await as(A,'select sum(amount)::int as balance from tok_pair_ledger')).rows[0].balance===0);
 await reject(rpc(B,'cancel_reward',{room_id:room,id:reward}),/본인/);
 await Promise.all([rpc(A,'cancel_reward',{room_id:room,id:reward}),rpc(A,'cancel_reward',{room_id:room,id:reward})]);
 ok((await as(A,'select sum(amount)::int as balance from tok_pair_ledger')).rows[0].balance===4);
 ok((await as(A,"select sum(amount)::int as earned from tok_pair_ledger where kind='earn'")).rows[0].earned===5);
 const diary=uuid(),photo=`${room}/${A}/${uuid()}`;await upload(A,photo);
 const entry={room_id:room,id:diary,entry_date:'2026-10-02',body:'한 줄 일기',image_path:photo,publish:false};await rpc(A,'diary',entry);
 ok((await as(B,'select * from tok_pair_diaries')).rows.length===0);
 ok((await as(B,'select * from storage.objects where name=$1',[photo])).rows.length===0);
 await reject(rpc(B,'reply',{room_id:room,id:uuid(),diary_id:diary,body:'몰래 보기'}),/공개/);
 await rpc(A,'diary',{...entry,publish:true});ok((await as(B,'select * from tok_pair_diaries')).rows.length===1);
 ok((await as(B,'select * from storage.objects where name=$1',[photo])).rows.length===1);
 await reject(rpc(B,'diary',{...entry,body:'상대가 덮어쓰기'}),/본인/);
 await reject(rpc(A,'diary',{...entry,id:uuid()}));
 const reply=uuid();await rpc(B,'reply',{room_id:room,id:reply,diary_id:diary,body:'수고했어'});
 await reject(rpc(A,'reply',{room_id:room,id:reply,diary_id:diary,body:'덮어쓰기'}),/본인/);
 await rpc(A,'delete_reply',{room_id:room,id:reply});ok((await as(A,'select * from tok_pair_replies')).rows.length===1);
 await rpc(B,'reply',{room_id:room,id:reply,diary_id:diary,body:'좋은 하루!'});
 await rpc(B,'delete_reply',{room_id:room,id:reply});ok((await as(A,'select * from tok_pair_replies')).rows.length===0);
 for(const t of ['rooms','members','plans','proofs','rewards','ledger','diaries','replies'])ok((await as(C,`select * from tok_pair_${t}`)).rows.length===0);
 ok((await as(C,'select * from storage.objects')).rows.length===0);
 await rpc(B,'delete_diary',{room_id:room,id:diary});ok((await as(A,'select * from tok_pair_diaries')).rows.length===1);
 await rpc(A,'delete_diary',{room_id:room,id:diary});ok((await as(B,'select * from storage.objects where name=$1',[photo])).rows.length===0);
 ok((await db.query('select * from tok_todos')).rows[0].completed===false);
 await reject(as(B,"insert into tok_pair_ledger(room_id,user_id,kind,amount,actor_id) values($1,$2,'earn',100,$2)",[room,B]));
 await db.close();console.log(`PASS: ${checks} authorization, idempotency, ledger, source privacy, diary and storage assertions (local PGlite; requests serialized)`);
})().catch(e=>{console.error(e);process.exit(1)});
