const fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
const install=async p=>p.evaluate(()=>{
 window.timerDB=window.timerDB||{session:null,intervals:[],ledger:{},finished:[]};window.timerFail=null;
 sb.rpc=async(name,a)=>{const db=timerDB,now=new Date().toISOString();if(window.timerDelay){const d=timerDelay;timerDelay=0;await new Promise(r=>setTimeout(r,d));}if(name==='tok_stopwatch_read')return {data:{session:db.session,intervals:db.intervals,server_now:new Date().toISOString()}};
 if(name==='tok_stopwatch_today')return {data:db.finished.filter(r=>r.day===a.p_day)};
 if(name==='tok_stopwatch_report')return {data:db.finished.filter(r=>r.day>=a.p_from&&r.day<=a.p_to)};
 if(name!=='tok_stopwatch_change')return {data:null};window.lastTimerRequest={...a};if(timerFail==='before'){timerFail=null;return {error:{message:'network failure'}};}
 if(!db.ledger[a.p_request]){if(a.p_action==='start'){if(!db.session){const t=todos.find(t=>t.id===a.p_todo);db.session={id:'session-'+Date.now(),user_id:'test',todo_id:t.id,snapshot:{title:t.title,group_id:t.group_id,group_name:'회사',category_id:t.tag_id,category_name:'행정',project_id:t.project_id,project_name:'목표'},state:'running',version:1,started_at:now,timezone:a.p_timezone};db.intervals=[{started_at:now,ended_at:null}];}}else{if(!db.session||db.session.version!==a.p_version)return {error:{message:'stale_session'}};const cut=a.p_stopped_at||now;if(a.p_action==='resume'){db.intervals.push({started_at:now,ended_at:null});db.session.state='running';}else {db.intervals.filter(i=>!i.ended_at).forEach(i=>i.ended_at=cut);db.session.state=a.p_action==='pause'?'paused':'finished';}db.session.version++;if(a.p_action==='finish'){db.finished.push({...db.session,day:todayStr(),milliseconds:db.intervals.reduce((n,i)=>n+Date.parse(i.ended_at)-Date.parse(i.started_at),0)});db.session=null;db.intervals=[];}}
 db.ledger[a.p_request]={session:structuredClone(db.session),server_now:now};}
 if(timerFail==='after'){timerFail=null;return {error:{message:'lost response'}};}return {data:db.ledger[a.p_request]};};
});
(async()=>{fs.mkdirSync('test-results/tracking',{recursive:true});const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const p=await b.newPage({viewport:{width:1366,height:768}}),errors=[];p.on('pageerror',e=>errors.push(e.message));try{
await fixture(p);await install(p);await p.evaluate(async()=>{mockRows.tok_todos=[{id:'t',title:'서류 정리 · 실제 원본',is_done:false,start_date:null,group_id:'g',tag_id:'c',project_id:'p'},{id:'done',title:'완료 제외',is_done:true}];mockRows.tok_someday=[{id:'s',title:'언젠가 제외'}];mockRows.tok_projects=[{id:'p',name:'목표'}];mockRows.tok_item_groups=[{id:'g',kind:'todo',name:'회사'}];mockRows.tok_habit_categories=[{id:'c',name:'행정'}];await loadAll();showPage('timer');await tracking.refresh();});
assert.equal(await p.locator('#pageSidebarItems [data-tracking-view]').count(),2);assert.equal(await p.locator('#trackingView').isVisible(),false);assert.equal(await p.locator('#trackingTodo option').count(),2);
await p.locator('#trackingSearch').fill('서류');await p.locator('#trackingTodo').selectOption('t');await p.screenshot({path:'test-results/tracking/measure-desktop.png'});const original=await p.evaluate(()=>JSON.stringify(mockRows.tok_todos));
await p.locator('[data-track=start]').click();await p.waitForFunction(()=>tracking.getState().session);assert.equal(await p.evaluate(()=>tracking.getState().session.state),'running');await p.evaluate(()=>{timerDB.intervals[0].started_at=new Date(Date.now()-65000).toISOString();});await p.evaluate(()=>tracking.refresh());assert.match(await p.locator('.tracking-clock').innerText(),/00:01:05/);
await p.evaluate(()=>showPage('home'));assert(await p.locator('#trackingProgress').isVisible());await p.screenshot({path:'test-results/tracking/progress-desktop.png'});await p.locator('#trackingProgress [data-track=pause]').click();assert.equal(await p.evaluate(()=>tracking.getState().session.state),'paused');const paused=await p.evaluate(()=>tracking.getState().intervals[0].ended_at);await p.waitForTimeout(1100);assert.equal(await p.evaluate(()=>tracking.getState().intervals[0].ended_at),paused);
await p.locator('#trackingProgress [data-track=open]').click();await p.locator('[data-track=resume]').click();assert.equal(await p.evaluate(()=>timerDB.intervals.length),2);
await p.evaluate(()=>{window.timerFail='after';});await p.locator('[data-track=finish]').click();assert(await p.locator('[data-track=retry]').isVisible());const stop=await p.evaluate(()=>tracking.getState().pending.p_stopped_at);await p.waitForTimeout(1100);await p.locator('[data-track=retry]').click();assert.equal(await p.evaluate(()=>timerDB.finished.length),1);assert.equal(await p.evaluate(()=>lastTimerRequest.p_stopped_at),stop);assert.equal(await p.evaluate(()=>JSON.stringify(mockRows.tok_todos)),original);assert.equal(await p.evaluate(()=>mockWrites.length),0);
await p.locator('#pageSidebarItems [data-tracking-view=stats]').focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.dataset.trackingView),'stats');assert.equal(await p.locator('#trackingSearch').count(),0);assert.equal(await p.locator('.tracking-summary').count(),5);await p.screenshot({path:'test-results/tracking/stats-desktop.png'});await p.locator('#sidebarRailToggle').click();assert.equal(await p.locator('.tracking-summary').count(),5);
await p.evaluate(()=>{showPage('todos');});assert(await p.evaluate(()=>itemMenuModel('todo','t').entries.some(x=>x.label==='타이머 시작')));for(const kind of ['someday'])assert.equal(await p.evaluate(kind=>itemMenuModel(kind,'s').entries.some(x=>x.label==='타이머 시작'),kind),false);
await p.evaluate(()=>tracking.start('t'));assert.equal(await p.evaluate(()=>tracking.getState().session.todo_id),'t');const sid=await p.evaluate(()=>timerDB.session.id);await p.evaluate(()=>tracking.start('t'));assert.equal(await p.evaluate(()=>timerDB.session.id),sid);
await p.evaluate(async()=>{mockRows.tok_todos.push({id:'other',title:'다른 할일',is_done:false});await loadAll();await tracking.start('other');});assert.match(await p.locator('#trackingMessage').innerText(),/종료하고 저장/);assert.equal(await p.evaluate(()=>timerDB.session.id),sid);
await p.evaluate(async()=>{window.timerFail='before';await tracking.getState();});await p.locator('[data-track=finish]').click();const pending=await p.evaluate(()=>tracking.getState().pending);assert(pending);await p.evaluate(()=>tracking.bind('other-user'));assert.equal(await p.evaluate(()=>tracking.getState().pending),null);await p.evaluate(async()=>{tracking.bind('test');await tracking.refresh();});assert.equal(await p.evaluate(()=>tracking.getState().pending.p_request),pending.p_request);await p.locator('[data-track=retry]').click();
// Browser reconnect: same mocked server state, pending/request state remains per owner.
const db=await p.evaluate(()=>timerDB);await p.reload();await fixture(p);await p.evaluate(db=>window.timerDB=db,db);await install(p);await p.evaluate(async()=>{showPage('timer');await tracking.refresh();});assert.equal(await p.evaluate(()=>tracking.getState().session),null);
for(const width of [390,760,761]){await p.setViewportSize({width,height:900});await p.evaluate(()=>{showPage('timer');tracking.select('measure');});assert.equal(await p.locator('#trackingView').isVisible(),width<=760);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);if(width===390)await p.screenshot({path:'test-results/tracking/measure-mobile.png'});}
await p.setViewportSize({width:390,height:844});await p.locator('#trackingView').selectOption('stats');await p.screenshot({path:'test-results/tracking/stats-mobile.png'});
assert.equal(await p.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);return ids.length-new Set(ids).size;}),0);for(const theme of ['white','black','cheese']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await p.screenshot({path:'test-results/tracking/stats-mobile-'+theme+'.png'});}await p.setViewportSize({width:1440,height:900});await p.evaluate(()=>tracking.select('measure'));await p.screenshot({path:'test-results/tracking/measure-1440.png'});assert.deepEqual(errors,[]);console.log('PASS stopwatch UI: independent pages, todo-only menu, source unchanged, pause/resume, response loss retry stop instant, account retry envelope, mobile, console/IDs');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
