const assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./period-fixture.cjs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await fixture(p);await p.evaluate(async()=>{mockRows.tok_events=[{id:'e',user_id:'test',title:'긴 제목의 주간 일정입니다',event_date:'2026-10-05',end_date:'2026-10-05',event_time:'09:00',end_time:'10:00',duration_minutes:60,all_day:false},{id:'overlap',user_id:'test',title:'동시에 진행되는 일정',event_date:'2026-10-05',end_date:'2026-10-05',event_time:'09:15',end_time:'10:15',duration_minutes:60,all_day:false},{id:'all',user_id:'test',title:'종일 일정',event_date:'2026-10-06',end_date:'2026-10-06',all_day:true}];await loadAll();showPage('schedule');calSelected='2026-10-05';calCursor='2026-10';scheduleViews.selectView('week');});
 for(const width of [1440,900,761,760,390,320]){await p.setViewportSize({width,height:900});await p.evaluate(()=>renderScheduleCalendar());const geometry=await p.locator('#scheduleTimeScroll').evaluate(el=>{const r=el.getBoundingClientRect();return {fits:el.scrollWidth<=el.clientWidth+1,days:[...el.querySelectorAll('.sv-day')].map(d=>{const x=d.getBoundingClientRect();return x.left>=r.left&&x.right<=r.right+1;}),axis:el.querySelectorAll('.schedule-week-axis').length,duplicate:el.querySelectorAll('.sv-day .tl-row-label').length};});assert(geometry.fits,JSON.stringify({width,...geometry}));assert.deepEqual(geometry.days,Array(7).fill(true));assert.equal(geometry.axis,1);assert.equal(geometry.duplicate,0);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'test-results/week-fit-'+width+'.png'});}
 await p.setViewportSize({width:1440,height:900});await p.evaluate(()=>renderScheduleCalendar());
 const source=await p.locator('#scheduleTimeDays [data-event-id=e]').boundingBox(),axis=await p.locator('#scheduleTimeDays [data-time-date="2026-10-07"]').boundingBox();await p.locator('#scheduleTimeScroll').evaluate(el=>el.scrollTop=0);const src=await p.locator('#scheduleTimeDays [data-event-id=e]').boundingBox();await p.mouse.move(src.x+3,src.y+10);await p.mouse.down();await p.mouse.move(axis.x+axis.width/2,src.y+10,{steps:12});await p.mouse.up();await p.waitForFunction(()=>mockRows.tok_events.find(e=>e.id==='e').event_date==='2026-10-07');assert.equal(await p.locator('#cev_title').isVisible(),false);
 await p.locator('#scheduleTimeDays .sv-event-open[data-id=overlap]').click();assert.equal(await p.locator('#cev_title').isVisible(),false);await p.keyboard.press('Escape');
 await p.locator('#scheduleModeToggle [data-schedule-view=day]').click();assert.equal(await p.locator('#scheduleTimeDays .sv-day').count(),1);assert.equal(await p.locator('.schedule-week-axis').count(),0);await p.locator('#scheduleModeToggle [data-schedule-view=month]').click();assert(await p.locator('#calGrid').isVisible());
 assert.deepEqual(errors,[]);console.log('seven visible days at 1440/900/761/760/390/320, one axis, overlap, actual date drag and detail, month/day isolation PASS');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
